#pragma once

#include <stdint.h>

/* ================= CAN ID Macros ================= */

#define CAN_ID_BPS_STATUS 0x1
#define CAN_ID_BPS_VT0_VOLTAGE_ARR 0x2
#define CAN_ID_BPS_VT1_VOLTAGE_ARR 0x3
#define CAN_ID_BPS_VT2_VOLTAGE_ARR 0x4
#define CAN_ID_BPS_VT3_VOLTAGE_ARR 0x5
#define CAN_ID_BPS_VT4_VOLTAGE_ARR 0x6
#define CAN_ID_BPS_VT5_VOLTAGE_ARR 0x7
#define CAN_ID_BPS_VT6_VOLTAGE_ARR 0x8
#define CAN_ID_BPS_VT7_VOLTAGE_ARR 0x9
#define CAN_ID_BPS_PACK_CURRENT 0xA
#define CAN_ID_BPS_VOLTAGE_AGGREGATE_ARR 0xB
#define CAN_ID_BPS_TEMPERATURE_AGGREGATE_ARR 0xC
#define CAN_ID_CHARGERINTERFACE_STATUS 0xE
#define CAN_ID_BPS_VT0_TEMPERATURE_ARR 0x10
#define CAN_ID_BPS_VT1_TEMPERATURE_ARR 0x11
#define CAN_ID_BPS_VT2_TEMPERATURE_ARR 0x12
#define CAN_ID_BPS_VT3_TEMPERATURE_ARR 0x13
#define CAN_ID_BPS_VT4_TEMPERATURE_ARR 0x14
#define CAN_ID_BPS_VT5_TEMPERATURE_ARR 0x15
#define CAN_ID_BPS_VT6_TEMPERATURE_ARR 0x16
#define CAN_ID_BPS_VT7_TEMPERATURE_ARR 0x17
#define CAN_ID_VCU_STATUS 0x18
#define CAN_ID_CONTROLS_STATUS 0x19
#define CAN_ID_BPS_PRECHARGE_VOLTAGES 0x20
#define CAN_ID_VCU_PRECHARGE_VOLTAGES 0x21
#define CAN_ID_PEDAL_STATUS 0x50
#define CAN_ID_DRIVER_INPUT_STATUS 0x60
#define CAN_ID_MPPT_A_POWERMEASUREMENTS 0x200
#define CAN_ID_MPPT_A_STATUS 0x201
#define CAN_ID_MPPT_A_SWEEPMEASUREMENTS 0x202
#define CAN_ID_MPPT_A_SETMODE 0x209
#define CAN_ID_MPPT_A_PERFORMSWEEP 0x210
#define CAN_ID_MPPT_A_SETOUTPUTVOLTAGELIMIT 0x211
#define CAN_ID_MPPT_A_SETOUTPUTCURRENTLIMIT 0x212
#define CAN_ID_MPPT_B_POWERMEASUREMENTS 0x220
#define CAN_ID_MPPT_B_STATUS 0x221
#define CAN_ID_MPPT_B_SWEEPMEASUREMENTS 0x222
#define CAN_ID_MPPT_B_SETMODE 0x229
#define CAN_ID_MPPT_B_PERFORMSWEEP 0x230
#define CAN_ID_MPPT_B_SETOUTPUTVOLTAGELIMIT 0x231
#define CAN_ID_MPPT_B_SETOUTPUTCURRENTLIMIT 0x232
#define CAN_ID_MPPT_C_POWERMEASUREMENTS 0x240
#define CAN_ID_MPPT_C_STATUS 0x241
#define CAN_ID_MPPT_C_SWEEPMEASUREMENTS 0x242
#define CAN_ID_MPPT_C_SETMODE 0x249
#define CAN_ID_MPPT_C_PERFORMSWEEP 0x250
#define CAN_ID_MPPT_C_SETOUTPUTVOLTAGELIMIT 0x251
#define CAN_ID_MPPT_C_SETOUTPUTCURRENTLIMIT 0x252
#define CAN_ID_LWS_STANDARD 0x2B0
#define CAN_ID_SUPP_BATTERY_STATUS 0x300
#define CAN_ID_SUPP_CHARGER_STATUS 0x301
#define CAN_ID_SUPP_VICOR_STATS 0x302
#define CAN_ID_PDU_STATUS_ARR 0x350
#define CAN_ID_PDU_SET_SWITCH_ARR 0x351
#define CAN_ID_PDU_SET_CURRENT_LIMIT_ARR 0x352
#define CAN_ID_MC_DRIVECOMMAND 0x401
#define CAN_ID_MC_POWERCOMMAND 0x402
#define CAN_ID_MC_RESETCOMMAND 0x403
#define CAN_ID_MC_INFO 0x420
#define CAN_ID_MC_STATUS 0x421
#define CAN_ID_MC_BUSMEASUREMENT 0x422
#define CAN_ID_MC_VELOCITYMEASUREMENT 0x423
#define CAN_ID_MC_PHASECURRENTMEASUREMENT 0x424
#define CAN_ID_MC_MOTORVOLTAGEVECTORMEASUREMENT 0x425
#define CAN_ID_MC_MOTORCURRENTVECTORMEASUREMENT 0x426
#define CAN_ID_MC_BACKEMFMEASUREMENTPREDICTION 0x427
#define CAN_ID_MC_15V_RAILMEASUREMENT 0x428
#define CAN_ID_MC_3V3_19V_RAILMEASUREMENT 0x429
#define CAN_ID_MC_MOTOR_TEMPMEASUREMENT 0x42B
#define CAN_ID_MC_DSPBOARDTEMPMEASUREMENT 0x42C
#define CAN_ID_MC_ODOMETERBUSAHMEASUREMENT 0x42E
#define CAN_ID_MC_SLIPSPEEDMEASUREMENT 0x437
#define CAN_ID_PUMP_STATUS 0x500
#define CAN_ID_COOLANT_TEMPERATURE 0x501
#define CAN_ID_RADIATOR_FANSPEED 0x502
#define CAN_ID_LV_CARRIER_STATUS 0x600
#define CAN_ID_BRAKE_PRESSURE_1 0x650
#define CAN_ID_BRAKE_PRESSURE_2 0x651
#define CAN_ID_LIGHTING_COMMAND 0x660
#define CAN_ID_LIGHTING_FRONT_STATUS 0x670
#define CAN_ID_LIGHTING_LEFT_STATUS 0x671
#define CAN_ID_LIGHTING_REAR_STATUS 0x672
#define CAN_ID_LIGHTING_RIGHT_STATUS 0x673
#define CAN_ID_LIGHTING_CANOPY_STATUS 0x674
#define CAN_ID_DISPLAY_STATUS 0x680
#define CAN_ID_TELEMETRY_STATUS 0x700
#define CAN_ID_BPS_TEMP_ADC_AGGREGATE_ARR 0x750
#define CAN_ID_SUPP_MEASUREMENTS_ADC 0x751
#define CAN_ID_SUPP_VICOR_MEASUREMENTS_ADC 0x752
#define CAN_ID_PEDAL_BRAKE_ADC 0x753
#define CAN_ID_PEDAL_ACCEL_ADC 0x754
#define CAN_ID_BPS_PACK_CURRENT_ADC 0x755
#define CAN_ID_BPS_BALANCE_DISCHARGE 0x7A0
#define CAN_ID_SET_MOTOR_CMD_SRC 0x7A1
#define CAN_ID_LWS_CONFIG 0x7C0
#define CAN_ID_ELCON_CONTROL 0x1806E5F4
#define CAN_ID_ELCON_CONTROL_MUX 0x1806E6F4
#define CAN_ID_ELCON_CCS_STATUS 0x18FF50E5

/* ================= CAN Length Macros ================= */

#define CAN_DLC_BPS_STATUS 8
#define CAN_DLC_BPS_VT0_VOLTAGE_ARR 4
#define CAN_DLC_BPS_VT1_VOLTAGE_ARR 4
#define CAN_DLC_BPS_VT2_VOLTAGE_ARR 4
#define CAN_DLC_BPS_VT3_VOLTAGE_ARR 4
#define CAN_DLC_BPS_VT4_VOLTAGE_ARR 4
#define CAN_DLC_BPS_VT5_VOLTAGE_ARR 4
#define CAN_DLC_BPS_VT6_VOLTAGE_ARR 4
#define CAN_DLC_BPS_VT7_VOLTAGE_ARR 4
#define CAN_DLC_BPS_PACK_CURRENT 5
#define CAN_DLC_BPS_VOLTAGE_AGGREGATE_ARR 6
#define CAN_DLC_BPS_TEMPERATURE_AGGREGATE_ARR 8
#define CAN_DLC_CHARGERINTERFACE_STATUS 5
#define CAN_DLC_BPS_VT0_TEMPERATURE_ARR 7
#define CAN_DLC_BPS_VT1_TEMPERATURE_ARR 7
#define CAN_DLC_BPS_VT2_TEMPERATURE_ARR 7
#define CAN_DLC_BPS_VT3_TEMPERATURE_ARR 7
#define CAN_DLC_BPS_VT4_TEMPERATURE_ARR 7
#define CAN_DLC_BPS_VT5_TEMPERATURE_ARR 7
#define CAN_DLC_BPS_VT6_TEMPERATURE_ARR 7
#define CAN_DLC_BPS_VT7_TEMPERATURE_ARR 7
#define CAN_DLC_VCU_STATUS 6
#define CAN_DLC_CONTROLS_STATUS 6
#define CAN_DLC_BPS_PRECHARGE_VOLTAGES 6
#define CAN_DLC_VCU_PRECHARGE_VOLTAGES 6
#define CAN_DLC_PEDAL_STATUS 6
#define CAN_DLC_DRIVER_INPUT_STATUS 2
#define CAN_DLC_MPPT_A_POWERMEASUREMENTS 8
#define CAN_DLC_MPPT_A_STATUS 5
#define CAN_DLC_MPPT_A_SWEEPMEASUREMENTS 6
#define CAN_DLC_MPPT_A_SETMODE 1
#define CAN_DLC_MPPT_A_PERFORMSWEEP 5
#define CAN_DLC_MPPT_A_SETOUTPUTVOLTAGELIMIT 2
#define CAN_DLC_MPPT_A_SETOUTPUTCURRENTLIMIT 2
#define CAN_DLC_MPPT_B_POWERMEASUREMENTS 8
#define CAN_DLC_MPPT_B_STATUS 5
#define CAN_DLC_MPPT_B_SWEEPMEASUREMENTS 6
#define CAN_DLC_MPPT_B_SETMODE 1
#define CAN_DLC_MPPT_B_PERFORMSWEEP 5
#define CAN_DLC_MPPT_B_SETOUTPUTVOLTAGELIMIT 2
#define CAN_DLC_MPPT_B_SETOUTPUTCURRENTLIMIT 2
#define CAN_DLC_MPPT_C_POWERMEASUREMENTS 8
#define CAN_DLC_MPPT_C_STATUS 5
#define CAN_DLC_MPPT_C_SWEEPMEASUREMENTS 6
#define CAN_DLC_MPPT_C_SETMODE 1
#define CAN_DLC_MPPT_C_PERFORMSWEEP 5
#define CAN_DLC_MPPT_C_SETOUTPUTVOLTAGELIMIT 2
#define CAN_DLC_MPPT_C_SETOUTPUTCURRENTLIMIT 2
#define CAN_DLC_LWS_STANDARD 5
#define CAN_DLC_SUPP_BATTERY_STATUS 6
#define CAN_DLC_SUPP_CHARGER_STATUS 6
#define CAN_DLC_SUPP_VICOR_STATS 5
#define CAN_DLC_PDU_STATUS_ARR 5
#define CAN_DLC_PDU_SET_SWITCH_ARR 1
#define CAN_DLC_PDU_SET_CURRENT_LIMIT_ARR 3
#define CAN_DLC_MC_DRIVECOMMAND 8
#define CAN_DLC_MC_POWERCOMMAND 4
#define CAN_DLC_MC_RESETCOMMAND 1
#define CAN_DLC_MC_INFO 8
#define CAN_DLC_MC_STATUS 8
#define CAN_DLC_MC_BUSMEASUREMENT 8
#define CAN_DLC_MC_VELOCITYMEASUREMENT 8
#define CAN_DLC_MC_PHASECURRENTMEASUREMENT 8
#define CAN_DLC_MC_MOTORVOLTAGEVECTORMEASUREMENT 8
#define CAN_DLC_MC_MOTORCURRENTVECTORMEASUREMENT 8
#define CAN_DLC_MC_BACKEMFMEASUREMENTPREDICTION 8
#define CAN_DLC_MC_15V_RAILMEASUREMENT 8
#define CAN_DLC_MC_3V3_19V_RAILMEASUREMENT 8
#define CAN_DLC_MC_MOTOR_TEMPMEASUREMENT 8
#define CAN_DLC_MC_DSPBOARDTEMPMEASUREMENT 8
#define CAN_DLC_MC_ODOMETERBUSAHMEASUREMENT 8
#define CAN_DLC_MC_SLIPSPEEDMEASUREMENT 8
#define CAN_DLC_PUMP_STATUS 6
#define CAN_DLC_COOLANT_TEMPERATURE 4
#define CAN_DLC_RADIATOR_FANSPEED 8
#define CAN_DLC_LV_CARRIER_STATUS 1
#define CAN_DLC_BRAKE_PRESSURE_1 5
#define CAN_DLC_BRAKE_PRESSURE_2 5
#define CAN_DLC_LIGHTING_COMMAND 1
#define CAN_DLC_LIGHTING_FRONT_STATUS 8
#define CAN_DLC_LIGHTING_LEFT_STATUS 8
#define CAN_DLC_LIGHTING_REAR_STATUS 8
#define CAN_DLC_LIGHTING_RIGHT_STATUS 8
#define CAN_DLC_LIGHTING_CANOPY_STATUS 8
#define CAN_DLC_DISPLAY_STATUS 2
#define CAN_DLC_TELEMETRY_STATUS 8
#define CAN_DLC_BPS_TEMP_ADC_AGGREGATE_ARR 4
#define CAN_DLC_SUPP_MEASUREMENTS_ADC 5
#define CAN_DLC_SUPP_VICOR_MEASUREMENTS_ADC 5
#define CAN_DLC_PEDAL_BRAKE_ADC 5
#define CAN_DLC_PEDAL_ACCEL_ADC 5
#define CAN_DLC_BPS_PACK_CURRENT_ADC 3
#define CAN_DLC_BPS_BALANCE_DISCHARGE 1
#define CAN_DLC_SET_MOTOR_CMD_SRC 1
#define CAN_DLC_LWS_CONFIG 2
#define CAN_DLC_ELCON_CONTROL 5
#define CAN_DLC_ELCON_CONTROL_MUX 8
#define CAN_DLC_ELCON_CCS_STATUS 5

/* ================= Value Table Enums ================= */

typedef enum {
    BPS_STATUS_BPS_FAULT_OK = 0,
    BPS_STATUS_BPS_FAULT_OVERVOLTAGE = 1,
    BPS_STATUS_BPS_FAULT_UNDERVOLTAGE = 2,
    BPS_STATUS_BPS_FAULT_REGEN = 3,
    BPS_STATUS_BPS_FAULT_OVERTEMPERATURE = 4,
    BPS_STATUS_BPS_FAULT_ELCON = 5,
    BPS_STATUS_BPS_FAULT_ARRAY_PRECHARGE_TIMEOUT = 6,
    BPS_STATUS_BPS_FAULT_INTERNAL_WATCHDOG = 7,
    BPS_STATUS_BPS_FAULT_SEGMENT_WATCHDOG = 8,
    BPS_STATUS_BPS_FAULT_HV_PLUS_CONTACTOR_SENSE = 9,
    BPS_STATUS_BPS_FAULT_HV_MINUS_CONTACTOR_SENSE = 10,
    BPS_STATUS_BPS_FAULT_ARRAY_CONTACTOR_SENSE = 11,
    BPS_STATUS_BPS_FAULT_ARRAY_PCHG_CONTACTOR_SENSE = 12,
    BPS_STATUS_BPS_FAULT_ESTOP_1 = 13,
    BPS_STATUS_BPS_FAULT_ESTOP_2 = 14,
    BPS_STATUS_BPS_FAULT_ESTOP_3 = 15,
    BPS_STATUS_BPS_FAULT_CHARGING_OVERCURRENT = 16,
    BPS_STATUS_BPS_FAULT_DISCHARGING_OVERCURRENT = 17,
    BPS_STATUS_BPS_FAULT_AMPERES_WATCHDOG = 18,
} bps_status_bps_fault_e;

typedef enum {
    BPS_STATUS_BPS_CHARGE_OK_NOT_OK = 0,
    BPS_STATUS_BPS_CHARGE_OK_OK = 1,
} bps_status_bps_charge_ok_e;

typedef enum {
    BPS_STATUS_BPS_REGEN_OK_NOT_OK = 0,
    BPS_STATUS_BPS_REGEN_OK_OK = 1,
} bps_status_bps_regen_ok_e;

typedef enum {
    BPS_STATUS_HV_PLUS_CONTACTOR_STATE_OPEN = 0,
    BPS_STATUS_HV_PLUS_CONTACTOR_STATE_CLOSED = 1,
} bps_status_hv_plus_contactor_state_e;

typedef enum {
    BPS_STATUS_HV_MINUS_CONTACTOR_STATE_OPEN = 0,
    BPS_STATUS_HV_MINUS_CONTACTOR_STATE_CLOSED = 1,
} bps_status_hv_minus_contactor_state_e;

typedef enum {
    BPS_STATUS_ARRAY_CONTACTOR_STATE_OPEN = 0,
    BPS_STATUS_ARRAY_CONTACTOR_STATE_CLOSED = 1,
} bps_status_array_contactor_state_e;

typedef enum {
    BPS_STATUS_ARRAY_PRECHARGE_CONTACTOR_STATE_OPEN = 0,
    BPS_STATUS_ARRAY_PRECHARGE_CONTACTOR_STATE_CLOSED = 1,
} bps_status_array_precharge_contactor_state_e;

typedef enum {
    BPS_STATUS_BPS_SEGMENT0_STATUS_OK = 0,
    BPS_STATUS_BPS_SEGMENT0_STATUS_FAULT = 1,
} bps_status_bps_segment0_status_e;

typedef enum {
    BPS_STATUS_BPS_SEGMENT1_STATUS_OK = 0,
    BPS_STATUS_BPS_SEGMENT1_STATUS_FAULT = 1,
} bps_status_bps_segment1_status_e;

typedef enum {
    BPS_STATUS_BPS_SEGMENT2_STATUS_OK = 0,
    BPS_STATUS_BPS_SEGMENT2_STATUS_FAULT = 1,
} bps_status_bps_segment2_status_e;

typedef enum {
    BPS_STATUS_BPS_SEGMENT3_STATUS_OK = 0,
    BPS_STATUS_BPS_SEGMENT3_STATUS_FAULT = 1,
} bps_status_bps_segment3_status_e;

typedef enum {
    BPS_STATUS_BPS_SEGMENT4_STATUS_OK = 0,
    BPS_STATUS_BPS_SEGMENT4_STATUS_FAULT = 1,
} bps_status_bps_segment4_status_e;

typedef enum {
    BPS_STATUS_BPS_SEGMENT5_STATUS_OK = 0,
    BPS_STATUS_BPS_SEGMENT5_STATUS_FAULT = 1,
} bps_status_bps_segment5_status_e;

typedef enum {
    BPS_STATUS_BPS_SEGMENT6_STATUS_OK = 0,
    BPS_STATUS_BPS_SEGMENT6_STATUS_FAULT = 1,
} bps_status_bps_segment6_status_e;

typedef enum {
    BPS_STATUS_BPS_SEGMENT7_STATUS_OK = 0,
    BPS_STATUS_BPS_SEGMENT7_STATUS_FAULT = 1,
} bps_status_bps_segment7_status_e;

typedef enum {
    BPS_VT0_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OK = 0,
    BPS_VT0_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_BQ_I2C_READ_ERROR = 1,
    BPS_VT0_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OUT_OF_BOUNDS = 2,
    BPS_VT0_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OVER_VOLTAGE = 3,
    BPS_VT0_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_UNDER_VOLTAGE = 4,
    BPS_VT0_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_MESSAGE_WATCHDOG = 5,
} bps_vt0_voltage_arr_bps_voltage_tap_fault_e;

typedef enum {
    BPS_VT1_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OK = 0,
    BPS_VT1_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_BQ_I2C_READ_ERROR = 1,
    BPS_VT1_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OUT_OF_BOUNDS = 2,
    BPS_VT1_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OVER_VOLTAGE = 3,
    BPS_VT1_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_UNDER_VOLTAGE = 4,
    BPS_VT1_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_MESSAGE_WATCHDOG = 5,
} bps_vt1_voltage_arr_bps_voltage_tap_fault_e;

typedef enum {
    BPS_VT2_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OK = 0,
    BPS_VT2_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_BQ_I2C_READ_ERROR = 1,
    BPS_VT2_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OUT_OF_BOUNDS = 2,
    BPS_VT2_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OVER_VOLTAGE = 3,
    BPS_VT2_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_UNDER_VOLTAGE = 4,
    BPS_VT2_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_MESSAGE_WATCHDOG = 5,
} bps_vt2_voltage_arr_bps_voltage_tap_fault_e;

typedef enum {
    BPS_VT3_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OK = 0,
    BPS_VT3_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_BQ_I2C_READ_ERROR = 1,
    BPS_VT3_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OUT_OF_BOUNDS = 2,
    BPS_VT3_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OVER_VOLTAGE = 3,
    BPS_VT3_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_UNDER_VOLTAGE = 4,
    BPS_VT3_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_MESSAGE_WATCHDOG = 5,
} bps_vt3_voltage_arr_bps_voltage_tap_fault_e;

typedef enum {
    BPS_VT4_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OK = 0,
    BPS_VT4_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_BQ_I2C_READ_ERROR = 1,
    BPS_VT4_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OUT_OF_BOUNDS = 2,
    BPS_VT4_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OVER_VOLTAGE = 3,
    BPS_VT4_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_UNDER_VOLTAGE = 4,
    BPS_VT4_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_MESSAGE_WATCHDOG = 5,
} bps_vt4_voltage_arr_bps_voltage_tap_fault_e;

typedef enum {
    BPS_VT5_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OK = 0,
    BPS_VT5_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_BQ_I2C_READ_ERROR = 1,
    BPS_VT5_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OUT_OF_BOUNDS = 2,
    BPS_VT5_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OVER_VOLTAGE = 3,
    BPS_VT5_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_UNDER_VOLTAGE = 4,
    BPS_VT5_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_MESSAGE_WATCHDOG = 5,
} bps_vt5_voltage_arr_bps_voltage_tap_fault_e;

typedef enum {
    BPS_VT6_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OK = 0,
    BPS_VT6_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_BQ_I2C_READ_ERROR = 1,
    BPS_VT6_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OUT_OF_BOUNDS = 2,
    BPS_VT6_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OVER_VOLTAGE = 3,
    BPS_VT6_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_UNDER_VOLTAGE = 4,
    BPS_VT6_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_MESSAGE_WATCHDOG = 5,
} bps_vt6_voltage_arr_bps_voltage_tap_fault_e;

typedef enum {
    BPS_VT7_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OK = 0,
    BPS_VT7_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_BQ_I2C_READ_ERROR = 1,
    BPS_VT7_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OUT_OF_BOUNDS = 2,
    BPS_VT7_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_OVER_VOLTAGE = 3,
    BPS_VT7_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_UNDER_VOLTAGE = 4,
    BPS_VT7_VOLTAGE_ARR_BPS_VOLTAGE_TAP_FAULT_MESSAGE_WATCHDOG = 5,
} bps_vt7_voltage_arr_bps_voltage_tap_fault_e;

typedef enum {
    BPS_PACK_CURRENT_BPS_AMPERES_FAULT_OK = 0,
    BPS_PACK_CURRENT_BPS_AMPERES_FAULT_OUT_OF_BOUNDS = 1,
    BPS_PACK_CURRENT_BPS_AMPERES_FAULT_OVER_CURRENT_DISCHARGE_ = 2,
    BPS_PACK_CURRENT_BPS_AMPERES_FAULT_OVER_CURRENT_CHARGE_ = 3,
    BPS_PACK_CURRENT_BPS_AMPERES_FAULT_MESSAGE_WATCHDOG = 4,
} bps_pack_current_bps_amperes_fault_e;

typedef enum {
    BPS_VOLTAGE_AGGREGATE_ARR_BPS_VOLTAGE_TAP_FAULT_OK = 0,
    BPS_VOLTAGE_AGGREGATE_ARR_BPS_VOLTAGE_TAP_FAULT_BQ_I2C_READ_ERROR = 1,
    BPS_VOLTAGE_AGGREGATE_ARR_BPS_VOLTAGE_TAP_FAULT_OUT_OF_BOUNDS = 2,
    BPS_VOLTAGE_AGGREGATE_ARR_BPS_VOLTAGE_TAP_FAULT_OVER_VOLTAGE = 3,
    BPS_VOLTAGE_AGGREGATE_ARR_BPS_VOLTAGE_TAP_FAULT_UNDER_VOLTAGE = 4,
    BPS_VOLTAGE_AGGREGATE_ARR_BPS_VOLTAGE_TAP_FAULT_MESSAGE_WATCHDOG = 5,
} bps_voltage_aggregate_arr_bps_voltage_tap_fault_e;

typedef enum {
    BPS_TEMPERATURE_AGGREGATE_ARR_BPS_TEMPERATURE_TAP_FAULT_OK = 0,
    BPS_TEMPERATURE_AGGREGATE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_GND_ = 1,
    BPS_TEMPERATURE_AGGREGATE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_VCC_ = 2,
    BPS_TEMPERATURE_AGGREGATE_ARR_BPS_TEMPERATURE_TAP_FAULT_DISCONNECTED = 3,
    BPS_TEMPERATURE_AGGREGATE_ARR_BPS_TEMPERATURE_TAP_FAULT_OVER_TEMPERATURE = 4,
    BPS_TEMPERATURE_AGGREGATE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_OVER_TEMPERATURE = 5,
    BPS_TEMPERATURE_AGGREGATE_ARR_BPS_TEMPERATURE_TAP_FAULT_UNDER_TEMPERATURE = 6,
    BPS_TEMPERATURE_AGGREGATE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_UNDER_TEMPERATURE = 7,
    BPS_TEMPERATURE_AGGREGATE_ARR_BPS_TEMPERATURE_TAP_FAULT_MESSAGE_WATCHDOG = 8,
} bps_temperature_aggregate_arr_bps_temperature_tap_fault_e;

typedef enum {
    CHARGERINTERFACE_STATUS_ELCON_HW_FAULT_OK = 0,
    CHARGERINTERFACE_STATUS_ELCON_HW_FAULT_FAULT = 1,
} chargerinterface_status_elcon_hw_fault_e;

typedef enum {
    CHARGERINTERFACE_STATUS_ELCON_OVER_TEMPERATURE_OK = 0,
    CHARGERINTERFACE_STATUS_ELCON_OVER_TEMPERATURE_FAULT = 1,
} chargerinterface_status_elcon_over_temperature_e;

typedef enum {
    CHARGERINTERFACE_STATUS_ELCON_INPUT_VOL_ERROR_OK = 0,
    CHARGERINTERFACE_STATUS_ELCON_INPUT_VOL_ERROR_FAULT = 1,
} chargerinterface_status_elcon_input_vol_error_e;

typedef enum {
    CHARGERINTERFACE_STATUS_ELCON_START_STATE_NOT_OK = 0,
    CHARGERINTERFACE_STATUS_ELCON_START_STATE_OK = 1,
} chargerinterface_status_elcon_start_state_e;

typedef enum {
    CHARGERINTERFACE_STATUS_ELCON_CMD_TIMEOUT_NOT_OK = 0,
    CHARGERINTERFACE_STATUS_ELCON_CMD_TIMEOUT_OK = 1,
} chargerinterface_status_elcon_cmd_timeout_e;

typedef enum {
    CHARGERINTERFACE_STATUS_ELCON_WATCHDOG_NOT_OK = 0,
    CHARGERINTERFACE_STATUS_ELCON_WATCHDOG_OK = 1,
} chargerinterface_status_elcon_watchdog_e;

typedef enum {
    BPS_VT0_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OK = 0,
    BPS_VT0_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_GND_ = 1,
    BPS_VT0_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_VCC_ = 2,
    BPS_VT0_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_DISCONNECTED = 3,
    BPS_VT0_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OVER_TEMPERATURE = 4,
    BPS_VT0_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_OVER_TEMPERATURE = 5,
    BPS_VT0_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_UNDER_TEMPERATURE = 6,
    BPS_VT0_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_UNDER_TEMPERATURE = 7,
    BPS_VT0_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_MESSAGE_WATCHDOG = 8,
} bps_vt0_temperature_arr_bps_temperature_tap_fault_e;

typedef enum {
    BPS_VT1_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OK = 0,
    BPS_VT1_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_GND_ = 1,
    BPS_VT1_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_VCC_ = 2,
    BPS_VT1_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_DISCONNECTED = 3,
    BPS_VT1_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OVER_TEMPERATURE = 4,
    BPS_VT1_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_OVER_TEMPERATURE = 5,
    BPS_VT1_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_UNDER_TEMPERATURE = 6,
    BPS_VT1_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_UNDER_TEMPERATURE = 7,
    BPS_VT1_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_MESSAGE_WATCHDOG = 8,
} bps_vt1_temperature_arr_bps_temperature_tap_fault_e;

typedef enum {
    BPS_VT2_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OK = 0,
    BPS_VT2_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_GND_ = 1,
    BPS_VT2_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_VCC_ = 2,
    BPS_VT2_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_DISCONNECTED = 3,
    BPS_VT2_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OVER_TEMPERATURE = 4,
    BPS_VT2_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_OVER_TEMPERATURE = 5,
    BPS_VT2_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_UNDER_TEMPERATURE = 6,
    BPS_VT2_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_UNDER_TEMPERATURE = 7,
    BPS_VT2_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_MESSAGE_WATCHDOG = 8,
} bps_vt2_temperature_arr_bps_temperature_tap_fault_e;

typedef enum {
    BPS_VT3_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OK = 0,
    BPS_VT3_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_GND_ = 1,
    BPS_VT3_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_VCC_ = 2,
    BPS_VT3_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_DISCONNECTED = 3,
    BPS_VT3_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OVER_TEMPERATURE = 4,
    BPS_VT3_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_OVER_TEMPERATURE = 5,
    BPS_VT3_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_UNDER_TEMPERATURE = 6,
    BPS_VT3_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_UNDER_TEMPERATURE = 7,
    BPS_VT3_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_MESSAGE_WATCHDOG = 8,
} bps_vt3_temperature_arr_bps_temperature_tap_fault_e;

typedef enum {
    BPS_VT4_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OK = 0,
    BPS_VT4_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_GND_ = 1,
    BPS_VT4_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_VCC_ = 2,
    BPS_VT4_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_DISCONNECTED = 3,
    BPS_VT4_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OVER_TEMPERATURE = 4,
    BPS_VT4_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_OVER_TEMPERATURE = 5,
    BPS_VT4_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_UNDER_TEMPERATURE = 6,
    BPS_VT4_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_UNDER_TEMPERATURE = 7,
    BPS_VT4_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_MESSAGE_WATCHDOG = 8,
} bps_vt4_temperature_arr_bps_temperature_tap_fault_e;

typedef enum {
    BPS_VT5_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OK = 0,
    BPS_VT5_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_GND_ = 1,
    BPS_VT5_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_VCC_ = 2,
    BPS_VT5_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_DISCONNECTED = 3,
    BPS_VT5_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OVER_TEMPERATURE = 4,
    BPS_VT5_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_OVER_TEMPERATURE = 5,
    BPS_VT5_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_UNDER_TEMPERATURE = 6,
    BPS_VT5_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_UNDER_TEMPERATURE = 7,
    BPS_VT5_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_MESSAGE_WATCHDOG = 8,
} bps_vt5_temperature_arr_bps_temperature_tap_fault_e;

typedef enum {
    BPS_VT6_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OK = 0,
    BPS_VT6_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_GND_ = 1,
    BPS_VT6_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_VCC_ = 2,
    BPS_VT6_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_DISCONNECTED = 3,
    BPS_VT6_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OVER_TEMPERATURE = 4,
    BPS_VT6_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_OVER_TEMPERATURE = 5,
    BPS_VT6_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_UNDER_TEMPERATURE = 6,
    BPS_VT6_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_UNDER_TEMPERATURE = 7,
    BPS_VT6_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_MESSAGE_WATCHDOG = 8,
} bps_vt6_temperature_arr_bps_temperature_tap_fault_e;

typedef enum {
    BPS_VT7_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OK = 0,
    BPS_VT7_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_GND_ = 1,
    BPS_VT7_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OUT_OF_BOUNDS_SHORT_TO_VCC_ = 2,
    BPS_VT7_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_DISCONNECTED = 3,
    BPS_VT7_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_OVER_TEMPERATURE = 4,
    BPS_VT7_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_OVER_TEMPERATURE = 5,
    BPS_VT7_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_UNDER_TEMPERATURE = 6,
    BPS_VT7_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_CHARGE_UNDER_TEMPERATURE = 7,
    BPS_VT7_TEMPERATURE_ARR_BPS_TEMPERATURE_TAP_FAULT_MESSAGE_WATCHDOG = 8,
} bps_vt7_temperature_arr_bps_temperature_tap_fault_e;

typedef enum {
    VCU_STATUS_VCU_FSM_STATE_INIT = 0,
    VCU_STATUS_VCU_FSM_STATE_FORWARD_DRIVE = 1,
    VCU_STATUS_VCU_FSM_STATE_NEUTRAL_DRIVE = 2,
    VCU_STATUS_VCU_FSM_STATE_REVERSE_DRIVE = 3,
    VCU_STATUS_VCU_FSM_STATE_REGEN = 4,
    VCU_STATUS_VCU_FSM_STATE_CRUISE_CONTROL = 5,
    VCU_STATUS_VCU_FSM_STATE_DISABLED = 6,
    VCU_STATUS_VCU_FSM_STATE_VEHICLE_NOT_READY = 7,
} vcu_status_vcu_fsm_state_e;

typedef enum {
    VCU_STATUS_MOTOR_READY_NOT_OK = 0,
    VCU_STATUS_MOTOR_READY_OK = 1,
} vcu_status_motor_ready_e;

typedef enum {
    VCU_STATUS_MOTOR_PRECHARGE_CONTACTOR_STATE_OPEN = 0,
    VCU_STATUS_MOTOR_PRECHARGE_CONTACTOR_STATE_CLOSED = 1,
} vcu_status_motor_precharge_contactor_state_e;

typedef enum {
    VCU_STATUS_MOTOR_CONTACTOR_STATE_OPEN = 0,
    VCU_STATUS_MOTOR_CONTACTOR_STATE_CLOSED = 1,
} vcu_status_motor_contactor_state_e;

typedef enum {
    VCU_STATUS_VCU_DRIVER_INPUT_WATCHDOG_NOT_OK = 0,
    VCU_STATUS_VCU_DRIVER_INPUT_WATCHDOG_OK = 1,
} vcu_status_vcu_driver_input_watchdog_e;

typedef enum {
    VCU_STATUS_VCU_PEDALS_WATCHDOG_NOT_OK = 0,
    VCU_STATUS_VCU_PEDALS_WATCHDOG_OK = 1,
} vcu_status_vcu_pedals_watchdog_e;

typedef enum {
    VCU_STATUS_VCU_BPS_WATCHDOG_NOT_OK = 0,
    VCU_STATUS_VCU_BPS_WATCHDOG_OK = 1,
} vcu_status_vcu_bps_watchdog_e;

typedef enum {
    VCU_STATUS_VCU_STEERING_ANGLE_WATCHDOG_NOT_OK = 0,
    VCU_STATUS_VCU_STEERING_ANGLE_WATCHDOG_OK = 1,
} vcu_status_vcu_steering_angle_watchdog_e;

typedef enum {
    VCU_STATUS_VCU_BPS_FAULT_DETECTED_OK = 0,
    VCU_STATUS_VCU_BPS_FAULT_DETECTED_FAULT = 1,
} vcu_status_vcu_bps_fault_detected_e;

typedef enum {
    VCU_STATUS_VCU_CONTROLS_FAULT_DETECTED_OK = 0,
    VCU_STATUS_VCU_CONTROLS_FAULT_DETECTED_FAULT = 1,
} vcu_status_vcu_controls_fault_detected_e;

typedef enum {
    VCU_STATUS_VCU_MTR_FAULT_DETECTED_OK = 0,
    VCU_STATUS_VCU_MTR_FAULT_DETECTED_FAULT = 1,
} vcu_status_vcu_mtr_fault_detected_e;

typedef enum {
    VCU_STATUS_VCU_PEDALS_FAULT_DETECTED_OK = 0,
    VCU_STATUS_VCU_PEDALS_FAULT_DETECTED_FAULT = 1,
} vcu_status_vcu_pedals_fault_detected_e;

typedef enum {
    VCU_STATUS_VCU_STEERING_FAULT_DETECTED_OK = 0,
    VCU_STATUS_VCU_STEERING_FAULT_DETECTED_FAULT = 1,
} vcu_status_vcu_steering_fault_detected_e;

typedef enum {
    VCU_STATUS_VCU_MOTORCOMMANDSOURCE_VCU = 0,
    VCU_STATUS_VCU_MOTORCOMMANDSOURCE_TRITIUM_EXTERNAL = 1,
} vcu_status_vcu_motorcommandsource_e;

typedef enum {
    VCU_STATUS_VCU_REGEN_ACTIVE_INACTIVE = 0,
    VCU_STATUS_VCU_REGEN_ACTIVE_ACTIVE = 1,
} vcu_status_vcu_regen_active_e;

typedef enum {
    VCU_STATUS_VCU_REGEN_OK_NOT_OK = 0,
    VCU_STATUS_VCU_REGEN_OK_OK = 1,
} vcu_status_vcu_regen_ok_e;

typedef enum {
    VCU_STATUS_VCU_MTR_PCHG_TIMEOUT_OK = 0,
    VCU_STATUS_VCU_MTR_PCHG_TIMEOUT_FAULT = 1,
} vcu_status_vcu_mtr_pchg_timeout_e;

typedef enum {
    VCU_STATUS_VCU_MTR_PCHG_CONT_TIMEOUT_OK = 0,
    VCU_STATUS_VCU_MTR_PCHG_CONT_TIMEOUT_FAULT = 1,
} vcu_status_vcu_mtr_pchg_cont_timeout_e;

typedef enum {
    VCU_STATUS_VCU_MTR_PCHG_CONT_MISMATCH_OK = 0,
    VCU_STATUS_VCU_MTR_PCHG_CONT_MISMATCH_FAULT = 1,
} vcu_status_vcu_mtr_pchg_cont_mismatch_e;

typedef enum {
    VCU_STATUS_VCU_MTR_CONT_MISMATCH_OK = 0,
    VCU_STATUS_VCU_MTR_CONT_MISMATCH_FAULT = 1,
} vcu_status_vcu_mtr_cont_mismatch_e;

typedef enum {
    VCU_STATUS_VCU_MTR_CONT_TIMEOUT_OK = 0,
    VCU_STATUS_VCU_MTR_CONT_TIMEOUT_FAULT = 1,
} vcu_status_vcu_mtr_cont_timeout_e;

typedef enum {
    VCU_STATUS_VCU_PCHG_OV_OK = 0,
    VCU_STATUS_VCU_PCHG_OV_FAULT = 1,
} vcu_status_vcu_pchg_ov_e;

typedef enum {
    VCU_STATUS_VCU_PCHG_UV_OK = 0,
    VCU_STATUS_VCU_PCHG_UV_FAULT = 1,
} vcu_status_vcu_pchg_uv_e;

typedef enum {
    VCU_STATUS_VCU_MTR_OV_OK = 0,
    VCU_STATUS_VCU_MTR_OV_FAULT = 1,
} vcu_status_vcu_mtr_ov_e;

typedef enum {
    VCU_STATUS_VCU_MTR_UV_OK = 0,
    VCU_STATUS_VCU_MTR_UV_FAULT = 1,
} vcu_status_vcu_mtr_uv_e;

typedef enum {
    VCU_STATUS_VCU_OTHER_FAULT_OK = 0,
    VCU_STATUS_VCU_OTHER_FAULT_FAULT = 1,
} vcu_status_vcu_other_fault_e;

typedef enum {
    VCU_STATUS_VCU_MTR_DIR_CHANGE_LOCKOUT_INACTIVE = 0,
    VCU_STATUS_VCU_MTR_DIR_CHANGE_LOCKOUT_ACTIVE = 1,
} vcu_status_vcu_mtr_dir_change_lockout_e;

typedef enum {
    VCU_STATUS_VCU_TIPPING_WARNING_INACTIVE = 0,
    VCU_STATUS_VCU_TIPPING_WARNING_ACTIVE = 1,
} vcu_status_vcu_tipping_warning_e;

typedef enum {
    VCU_STATUS_VCU_WARN_REGEN_NOT_ALLOW_INACTIVE = 0,
    VCU_STATUS_VCU_WARN_REGEN_NOT_ALLOW_ACTIVE = 1,
} vcu_status_vcu_warn_regen_not_allow_e;

typedef enum {
    VCU_STATUS_VCU_WARN_REGEN_NOT_EN_INACTIVE = 0,
    VCU_STATUS_VCU_WARN_REGEN_NOT_EN_ACTIVE = 1,
} vcu_status_vcu_warn_regen_not_en_e;

typedef enum {
    VCU_STATUS_VCU_FSM_INP_BRAKE_FALSE = 0,
    VCU_STATUS_VCU_FSM_INP_BRAKE_TRUE = 1,
} vcu_status_vcu_fsm_inp_brake_e;

typedef enum {
    VCU_STATUS_VCU_FSM_INP_PCHG_OK_FALSE = 0,
    VCU_STATUS_VCU_FSM_INP_PCHG_OK_TRUE = 1,
} vcu_status_vcu_fsm_inp_pchg_ok_e;

typedef enum {
    VCU_STATUS_VCU_FSM_INP_CRUISE_REQ_FALSE = 0,
    VCU_STATUS_VCU_FSM_INP_CRUISE_REQ_TRUE = 1,
} vcu_status_vcu_fsm_inp_cruise_req_e;

typedef enum {
    VCU_STATUS_VCU_FSM_INP_REGEN_REQ_FALSE = 0,
    VCU_STATUS_VCU_FSM_INP_REGEN_REQ_TRUE = 1,
} vcu_status_vcu_fsm_inp_regen_req_e;

typedef enum {
    VCU_STATUS_VCU_FSM_INP_REGEN_ENABLE_FALSE = 0,
    VCU_STATUS_VCU_FSM_INP_REGEN_ENABLE_TRUE = 1,
} vcu_status_vcu_fsm_inp_regen_enable_e;

typedef enum {
    VCU_STATUS_VCU_FSM_INP_REGEN_RDY_FALSE = 0,
    VCU_STATUS_VCU_FSM_INP_REGEN_RDY_TRUE = 1,
} vcu_status_vcu_fsm_inp_regen_rdy_e;

typedef enum {
    VCU_STATUS_VCU_FSM_INP_FORWARD_FALSE = 0,
    VCU_STATUS_VCU_FSM_INP_FORWARD_TRUE = 1,
} vcu_status_vcu_fsm_inp_forward_e;

typedef enum {
    VCU_STATUS_VCU_FSM_INP_NEUTRAL_FALSE = 0,
    VCU_STATUS_VCU_FSM_INP_NEUTRAL_TRUE = 1,
} vcu_status_vcu_fsm_inp_neutral_e;

typedef enum {
    VCU_STATUS_VCU_FSM_INP_REVERSE_FALSE = 0,
    VCU_STATUS_VCU_FSM_INP_REVERSE_TRUE = 1,
} vcu_status_vcu_fsm_inp_reverse_e;

typedef enum {
    CONTROLS_STATUS_CONTROLS_LEADER_FAULT_OK = 0,
    CONTROLS_STATUS_CONTROLS_LEADER_FAULT_BOSCH_LWS_WATCHDOG = 1,
    CONTROLS_STATUS_CONTROLS_LEADER_FAULT_BPS_WATCHDOG = 2,
    CONTROLS_STATUS_CONTROLS_LEADER_FAULT_INVALID_DRIVER_INPUTS = 3,
    CONTROLS_STATUS_CONTROLS_LEADER_FAULT_LIGHTING_BOARD_FAULT = 4,
    CONTROLS_STATUS_CONTROLS_LEADER_FAULT_LIGHTING_BOARD_WATCHDOG = 5,
} controls_status_controls_leader_fault_e;

typedef enum {
    CONTROLS_STATUS_LIGHTINGBOARD_FRONT_STATUS_OK = 0,
    CONTROLS_STATUS_LIGHTINGBOARD_FRONT_STATUS_ADDR_LED_UNDERCURRENT = 1,
    CONTROLS_STATUS_LIGHTINGBOARD_FRONT_STATUS_LED0_UNDERCURRENT = 2,
    CONTROLS_STATUS_LIGHTINGBOARD_FRONT_STATUS_LED1_UNDERCURRENT = 3,
    CONTROLS_STATUS_LIGHTINGBOARD_FRONT_STATUS_ADDR_LED_OVERCURRENT = 4,
    CONTROLS_STATUS_LIGHTINGBOARD_FRONT_STATUS_LED0_OVERCURRENT = 5,
    CONTROLS_STATUS_LIGHTINGBOARD_FRONT_STATUS_LED1_OVERCURRENT = 6,
    CONTROLS_STATUS_LIGHTINGBOARD_FRONT_STATUS_LIGHT_COMMAND_WATCHDOG = 7,
    CONTROLS_STATUS_LIGHTINGBOARD_FRONT_STATUS_WATCHDOG = 8,
} controls_status_lightingboard_front_status_e;

typedef enum {
    CONTROLS_STATUS_LIGHTINGBOARD_LEFT_STATUS_OK = 0,
    CONTROLS_STATUS_LIGHTINGBOARD_LEFT_STATUS_ADDR_LED_UNDERCURRENT = 1,
    CONTROLS_STATUS_LIGHTINGBOARD_LEFT_STATUS_LED0_UNDERCURRENT = 2,
    CONTROLS_STATUS_LIGHTINGBOARD_LEFT_STATUS_LED1_UNDERCURRENT = 3,
    CONTROLS_STATUS_LIGHTINGBOARD_LEFT_STATUS_ADDR_LED_OVERCURRENT = 4,
    CONTROLS_STATUS_LIGHTINGBOARD_LEFT_STATUS_LED0_OVERCURRENT = 5,
    CONTROLS_STATUS_LIGHTINGBOARD_LEFT_STATUS_LED1_OVERCURRENT = 6,
    CONTROLS_STATUS_LIGHTINGBOARD_LEFT_STATUS_LIGHT_COMMAND_WATCHDOG = 7,
    CONTROLS_STATUS_LIGHTINGBOARD_LEFT_STATUS_WATCHDOG = 8,
} controls_status_lightingboard_left_status_e;

typedef enum {
    CONTROLS_STATUS_LIGHTINGBOARD_RIGHT_STATUS_OK = 0,
    CONTROLS_STATUS_LIGHTINGBOARD_RIGHT_STATUS_ADDR_LED_UNDERCURRENT = 1,
    CONTROLS_STATUS_LIGHTINGBOARD_RIGHT_STATUS_LED0_UNDERCURRENT = 2,
    CONTROLS_STATUS_LIGHTINGBOARD_RIGHT_STATUS_LED1_UNDERCURRENT = 3,
    CONTROLS_STATUS_LIGHTINGBOARD_RIGHT_STATUS_ADDR_LED_OVERCURRENT = 4,
    CONTROLS_STATUS_LIGHTINGBOARD_RIGHT_STATUS_LED0_OVERCURRENT = 5,
    CONTROLS_STATUS_LIGHTINGBOARD_RIGHT_STATUS_LED1_OVERCURRENT = 6,
    CONTROLS_STATUS_LIGHTINGBOARD_RIGHT_STATUS_LIGHT_COMMAND_WATCHDOG = 7,
    CONTROLS_STATUS_LIGHTINGBOARD_RIGHT_STATUS_WATCHDOG = 8,
} controls_status_lightingboard_right_status_e;

typedef enum {
    CONTROLS_STATUS_LIGHTINGBOARD_REAR_STATUS_OK = 0,
    CONTROLS_STATUS_LIGHTINGBOARD_REAR_STATUS_ADDR_LED_UNDERCURRENT = 1,
    CONTROLS_STATUS_LIGHTINGBOARD_REAR_STATUS_LED0_UNDERCURRENT = 2,
    CONTROLS_STATUS_LIGHTINGBOARD_REAR_STATUS_LED1_UNDERCURRENT = 3,
    CONTROLS_STATUS_LIGHTINGBOARD_REAR_STATUS_ADDR_LED_OVERCURRENT = 4,
    CONTROLS_STATUS_LIGHTINGBOARD_REAR_STATUS_LED0_OVERCURRENT = 5,
    CONTROLS_STATUS_LIGHTINGBOARD_REAR_STATUS_LED1_OVERCURRENT = 6,
    CONTROLS_STATUS_LIGHTINGBOARD_REAR_STATUS_LIGHT_COMMAND_WATCHDOG = 7,
    CONTROLS_STATUS_LIGHTINGBOARD_REAR_STATUS_WATCHDOG = 8,
} controls_status_lightingboard_rear_status_e;

typedef enum {
    CONTROLS_STATUS_LIGHTINGBOARD_CANOPY_STATUS_OK = 0,
    CONTROLS_STATUS_LIGHTINGBOARD_CANOPY_STATUS_ADDR_LED_UNDERCURRENT = 1,
    CONTROLS_STATUS_LIGHTINGBOARD_CANOPY_STATUS_LED0_UNDERCURRENT = 2,
    CONTROLS_STATUS_LIGHTINGBOARD_CANOPY_STATUS_LED1_UNDERCURRENT = 3,
    CONTROLS_STATUS_LIGHTINGBOARD_CANOPY_STATUS_ADDR_LED_OVERCURRENT = 4,
    CONTROLS_STATUS_LIGHTINGBOARD_CANOPY_STATUS_LED0_OVERCURRENT = 5,
    CONTROLS_STATUS_LIGHTINGBOARD_CANOPY_STATUS_LED1_OVERCURRENT = 6,
    CONTROLS_STATUS_LIGHTINGBOARD_CANOPY_STATUS_LIGHT_COMMAND_WATCHDOG = 7,
    CONTROLS_STATUS_LIGHTINGBOARD_CANOPY_STATUS_WATCHDOG = 8,
} controls_status_lightingboard_canopy_status_e;

typedef enum {
    PEDAL_STATUS_ACCELPEDAL_MAIN_FAULT_OK = 0,
    PEDAL_STATUS_ACCELPEDAL_MAIN_FAULT_FAULT = 1,
} pedal_status_accelpedal_main_fault_e;

typedef enum {
    PEDAL_STATUS_ACCELPEDAL_REDUNDANT_FAULT_OK = 0,
    PEDAL_STATUS_ACCELPEDAL_REDUNDANT_FAULT_FAULT = 1,
} pedal_status_accelpedal_redundant_fault_e;

typedef enum {
    PEDAL_STATUS_BRAKEPEDAL_MAIN_FAULT_OK = 0,
    PEDAL_STATUS_BRAKEPEDAL_MAIN_FAULT_FAULT = 1,
} pedal_status_brakepedal_main_fault_e;

typedef enum {
    PEDAL_STATUS_BRAKEPEDAL_REDUNDANT_FAULT_OK = 0,
    PEDAL_STATUS_BRAKEPEDAL_REDUNDANT_FAULT_FAULT = 1,
} pedal_status_brakepedal_redundant_fault_e;

typedef enum {
    PEDAL_STATUS_BRAKE_PRESSURE_1_FAULT_OK = 0,
    PEDAL_STATUS_BRAKE_PRESSURE_1_FAULT_FAULT = 1,
} pedal_status_brake_pressure_1_fault_e;

typedef enum {
    PEDAL_STATUS_BRAKE_PRESSURE_2_FAULT_OK = 0,
    PEDAL_STATUS_BRAKE_PRESSURE_2_FAULT_FAULT = 1,
} pedal_status_brake_pressure_2_fault_e;

typedef enum {
    DRIVER_INPUT_STATUS_IGNITION_ARRAY__ = 0,
    DRIVER_INPUT_STATUS_IGNITION_ARRAY_SELECTED = 1,
} driver_input_status_ignition_array_e;

typedef enum {
    DRIVER_INPUT_STATUS_IGNITION_MOTOR__ = 0,
    DRIVER_INPUT_STATUS_IGNITION_MOTOR_SELECTED = 1,
} driver_input_status_ignition_motor_e;

typedef enum {
    DRIVER_INPUT_STATUS_IGNITION_OFF__ = 0,
    DRIVER_INPUT_STATUS_IGNITION_OFF_SELECTED = 1,
} driver_input_status_ignition_off_e;

typedef enum {
    DRIVER_INPUT_STATUS_CRUISE_ENABLE_DISABLED = 0,
    DRIVER_INPUT_STATUS_CRUISE_ENABLE_ENABLED = 1,
} driver_input_status_cruise_enable_e;

typedef enum {
    DRIVER_INPUT_STATUS_CRUISE_SET__ = 0,
    DRIVER_INPUT_STATUS_CRUISE_SET_PRESSED = 1,
} driver_input_status_cruise_set_e;

typedef enum {
    DRIVER_INPUT_STATUS_GEAR_FORWARD__ = 0,
    DRIVER_INPUT_STATUS_GEAR_FORWARD_SELECTED = 1,
} driver_input_status_gear_forward_e;

typedef enum {
    DRIVER_INPUT_STATUS_GEAR_NEUTRAL__ = 0,
    DRIVER_INPUT_STATUS_GEAR_NEUTRAL_SELECTED = 1,
} driver_input_status_gear_neutral_e;

typedef enum {
    DRIVER_INPUT_STATUS_GEAR_REVERSE__ = 0,
    DRIVER_INPUT_STATUS_GEAR_REVERSE_SELECTED = 1,
} driver_input_status_gear_reverse_e;

typedef enum {
    DRIVER_INPUT_STATUS_HAZARD_PRESSED_OFF = 0,
    DRIVER_INPUT_STATUS_HAZARD_PRESSED_ON = 1,
} driver_input_status_hazard_pressed_e;

typedef enum {
    DRIVER_INPUT_STATUS_HORN_PRESSED_OFF = 0,
    DRIVER_INPUT_STATUS_HORN_PRESSED_ON = 1,
} driver_input_status_horn_pressed_e;

typedef enum {
    DRIVER_INPUT_STATUS_BLINKER_LEFT__ = 0,
    DRIVER_INPUT_STATUS_BLINKER_LEFT_SELECTED = 1,
} driver_input_status_blinker_left_e;

typedef enum {
    DRIVER_INPUT_STATUS_BLINKER_RIGHT__ = 0,
    DRIVER_INPUT_STATUS_BLINKER_RIGHT_SELECTED = 1,
} driver_input_status_blinker_right_e;

typedef enum {
    DRIVER_INPUT_STATUS_PUSHTOTALK_PRESSED__ = 0,
    DRIVER_INPUT_STATUS_PUSHTOTALK_PRESSED_PRESSED = 1,
} driver_input_status_pushtotalk_pressed_e;

typedef enum {
    DRIVER_INPUT_STATUS_REGEN_ACTIVATE__ = 0,
    DRIVER_INPUT_STATUS_REGEN_ACTIVATE_PRESSED = 1,
} driver_input_status_regen_activate_e;

typedef enum {
    DRIVER_INPUT_STATUS_REGEN_ENABLE_DISABLED = 0,
    DRIVER_INPUT_STATUS_REGEN_ENABLE_ENABLED = 1,
} driver_input_status_regen_enable_e;

typedef enum {
    MPPT_A_STATUS_MPPT_MODE_CONSTANT_INPUT_VOLTAGE = 0,
    MPPT_A_STATUS_MPPT_MODE_CONSTANT_INPUT_CURRENT = 1,
    MPPT_A_STATUS_MPPT_MODE_MINIMUM_INPUT_CURRENT = 2,
    MPPT_A_STATUS_MPPT_MODE_CONSTANT_OUTPUT_VOLTAGE = 3,
    MPPT_A_STATUS_MPPT_MODE_CONSTANT_OUTPUT_CURRENT = 4,
    MPPT_A_STATUS_MPPT_MODE_TEMPERATURE_DE_RATING = 5,
    MPPT_A_STATUS_MPPT_MODE_FAULT = 6,
} mppt_a_status_mppt_mode_e;

typedef enum {
    MPPT_A_STATUS_MPPT_FAULT_OK = 0,
    MPPT_A_STATUS_MPPT_FAULT_CONFIGURATION_ERROR = 1,
    MPPT_A_STATUS_MPPT_FAULT_INPUT_OVER_VOLTAGE = 2,
    MPPT_A_STATUS_MPPT_FAULT_OUTPUT_OVER_VOLTAGE = 3,
    MPPT_A_STATUS_MPPT_FAULT_OUTPUT_OVER_CURRENT = 4,
    MPPT_A_STATUS_MPPT_FAULT_INPUT_OVER_CURRENT = 5,
    MPPT_A_STATUS_MPPT_FAULT_INPUT_UNDER_CURRENT = 6,
    MPPT_A_STATUS_MPPT_FAULT_PHASE_OVER_CURRENT = 7,
    MPPT_A_STATUS_MPPT_FAULT_UNKNOWN_FAULT = 8,
} mppt_a_status_mppt_fault_e;

typedef enum {
    MPPT_A_STATUS_MPPT_ENABLED_DISABLED = 0,
    MPPT_A_STATUS_MPPT_ENABLED_ENABLED = 1,
    MPPT_A_STATUS_MPPT_ENABLED_ENABLED_CONSTANT_VOLTAGE = 2,
} mppt_a_status_mppt_enabled_e;

typedef enum {
    MPPT_A_SETMODE_MPPT_SET_ENABLE_DISABLED = 0,
    MPPT_A_SETMODE_MPPT_SET_ENABLE_ENABLED = 1,
    MPPT_A_SETMODE_MPPT_SET_ENABLE_ENABLED_CONSTANT_VOLTAGE = 2,
} mppt_a_setmode_mppt_set_enable_e;

typedef enum {
    MPPT_B_STATUS_MPPT_MODE_CONSTANT_INPUT_VOLTAGE = 0,
    MPPT_B_STATUS_MPPT_MODE_CONSTANT_INPUT_CURRENT = 1,
    MPPT_B_STATUS_MPPT_MODE_MINIMUM_INPUT_CURRENT = 2,
    MPPT_B_STATUS_MPPT_MODE_CONSTANT_OUTPUT_VOLTAGE = 3,
    MPPT_B_STATUS_MPPT_MODE_CONSTANT_OUTPUT_CURRENT = 4,
    MPPT_B_STATUS_MPPT_MODE_TEMPERATURE_DE_RATING = 5,
    MPPT_B_STATUS_MPPT_MODE_FAULT = 6,
} mppt_b_status_mppt_mode_e;

typedef enum {
    MPPT_B_STATUS_MPPT_FAULT_OK = 0,
    MPPT_B_STATUS_MPPT_FAULT_CONFIGURATION_ERROR = 1,
    MPPT_B_STATUS_MPPT_FAULT_INPUT_OVER_VOLTAGE = 2,
    MPPT_B_STATUS_MPPT_FAULT_OUTPUT_OVER_VOLTAGE = 3,
    MPPT_B_STATUS_MPPT_FAULT_OUTPUT_OVER_CURRENT = 4,
    MPPT_B_STATUS_MPPT_FAULT_INPUT_OVER_CURRENT = 5,
    MPPT_B_STATUS_MPPT_FAULT_INPUT_UNDER_CURRENT = 6,
    MPPT_B_STATUS_MPPT_FAULT_PHASE_OVER_CURRENT = 7,
    MPPT_B_STATUS_MPPT_FAULT_UNKNOWN_FAULT = 8,
} mppt_b_status_mppt_fault_e;

typedef enum {
    MPPT_B_STATUS_MPPT_ENABLED_DISABLED = 0,
    MPPT_B_STATUS_MPPT_ENABLED_ENABLED = 1,
    MPPT_B_STATUS_MPPT_ENABLED_ENABLED_CONSTANT_VOLTAGE = 2,
} mppt_b_status_mppt_enabled_e;

typedef enum {
    MPPT_B_SETMODE_MPPT_SET_ENABLE_DISABLED = 0,
    MPPT_B_SETMODE_MPPT_SET_ENABLE_ENABLED = 1,
    MPPT_B_SETMODE_MPPT_SET_ENABLE_ENABLED_CONSTANT_VOLTAGE = 2,
} mppt_b_setmode_mppt_set_enable_e;

typedef enum {
    MPPT_C_STATUS_MPPT_MODE_CONSTANT_INPUT_VOLTAGE = 0,
    MPPT_C_STATUS_MPPT_MODE_CONSTANT_INPUT_CURRENT = 1,
    MPPT_C_STATUS_MPPT_MODE_MINIMUM_INPUT_CURRENT = 2,
    MPPT_C_STATUS_MPPT_MODE_CONSTANT_OUTPUT_VOLTAGE = 3,
    MPPT_C_STATUS_MPPT_MODE_CONSTANT_OUTPUT_CURRENT = 4,
    MPPT_C_STATUS_MPPT_MODE_TEMPERATURE_DE_RATING = 5,
    MPPT_C_STATUS_MPPT_MODE_FAULT = 6,
} mppt_c_status_mppt_mode_e;

typedef enum {
    MPPT_C_STATUS_MPPT_FAULT_OK = 0,
    MPPT_C_STATUS_MPPT_FAULT_CONFIGURATION_ERROR = 1,
    MPPT_C_STATUS_MPPT_FAULT_INPUT_OVER_VOLTAGE = 2,
    MPPT_C_STATUS_MPPT_FAULT_OUTPUT_OVER_VOLTAGE = 3,
    MPPT_C_STATUS_MPPT_FAULT_OUTPUT_OVER_CURRENT = 4,
    MPPT_C_STATUS_MPPT_FAULT_INPUT_OVER_CURRENT = 5,
    MPPT_C_STATUS_MPPT_FAULT_INPUT_UNDER_CURRENT = 6,
    MPPT_C_STATUS_MPPT_FAULT_PHASE_OVER_CURRENT = 7,
    MPPT_C_STATUS_MPPT_FAULT_UNKNOWN_FAULT = 8,
} mppt_c_status_mppt_fault_e;

typedef enum {
    MPPT_C_STATUS_MPPT_ENABLED_DISABLED = 0,
    MPPT_C_STATUS_MPPT_ENABLED_ENABLED = 1,
    MPPT_C_STATUS_MPPT_ENABLED_ENABLED_CONSTANT_VOLTAGE = 2,
} mppt_c_status_mppt_enabled_e;

typedef enum {
    MPPT_C_SETMODE_MPPT_SET_ENABLE_DISABLED = 0,
    MPPT_C_SETMODE_MPPT_SET_ENABLE_ENABLED = 1,
    MPPT_C_SETMODE_MPPT_SET_ENABLE_ENABLED_CONSTANT_VOLTAGE = 2,
} mppt_c_setmode_mppt_set_enable_e;

typedef enum {
    LWS_STANDARD_LWS_FAULT_OK = 0,
    LWS_STANDARD_LWS_FAULT_INTERNAL_FAULT = 1,
} lws_standard_lws_fault_e;

typedef enum {
    LWS_STANDARD_LWS_CALIBRATIONSTAUS_SENSOR_NOT_CALIBRATED = 0,
    LWS_STANDARD_LWS_CALIBRATIONSTAUS_SENSOR_CALIBRATED = 1,
} lws_standard_lws_calibrationstaus_e;

typedef enum {
    LWS_STANDARD_LWS_TRIMMING_STATUS_FAULT_SENSOR_NOT_TRIMMED = 0,
    LWS_STANDARD_LWS_TRIMMING_STATUS_SENSOR_TRIMMED = 1,
} lws_standard_lws_trimming_status_e;

typedef enum {
    SUPP_BATTERY_STATUS_SUPPLEMENTAL_BATTERY_FAULT_OK = 0,
    SUPP_BATTERY_STATUS_SUPPLEMENTAL_BATTERY_FAULT_UNDER_VOLTAGE = 1,
    SUPP_BATTERY_STATUS_SUPPLEMENTAL_BATTERY_FAULT_OVER_VOLTAGE = 2,
    SUPP_BATTERY_STATUS_SUPPLEMENTAL_BATTERY_FAULT_OVER_CURRENT_DISCHARGE_ = 3,
    SUPP_BATTERY_STATUS_SUPPLEMENTAL_BATTERY_FAULT_OVER_CURRENT_CHARGE_ = 4,
    SUPP_BATTERY_STATUS_SUPPLEMENTAL_BATTERY_FAULT_UNKNOWN_FAULT = 5,
} supp_battery_status_supplemental_battery_fault_e;

typedef enum {
    SUPP_CHARGER_STATUS_SUPPLEMENTAL_CHARGER_STATUS_CHARGE_DISABLED = 0,
    SUPP_CHARGER_STATUS_SUPPLEMENTAL_CHARGER_STATUS_TRICKLE_CHARGING = 1,
    SUPP_CHARGER_STATUS_SUPPLEMENTAL_CHARGER_STATUS_PRECHARGE = 2,
    SUPP_CHARGER_STATUS_SUPPLEMENTAL_CHARGER_STATUS_FAST_CHARGING = 3,
    SUPP_CHARGER_STATUS_SUPPLEMENTAL_CHARGER_STATUS_TAPER = 4,
    SUPP_CHARGER_STATUS_SUPPLEMENTAL_CHARGER_STATUS_ERROR = 5,
    SUPP_CHARGER_STATUS_SUPPLEMENTAL_CHARGER_STATUS_TOPPING_OFF = 6,
    SUPP_CHARGER_STATUS_SUPPLEMENTAL_CHARGER_STATUS_DONE = 7,
} supp_charger_status_supplemental_charger_status_e;

typedef enum {
    SUPP_CHARGER_STATUS_BQ25756E_ERROR_OK = 0,
    SUPP_CHARGER_STATUS_BQ25756E_ERROR_I2C_ERROR = 1,
    SUPP_CHARGER_STATUS_BQ25756E_ERROR_INPUT_UV = 2,
    SUPP_CHARGER_STATUS_BQ25756E_ERROR_INPUT_OV = 3,
    SUPP_CHARGER_STATUS_BQ25756E_ERROR_BATTERY_OC = 4,
    SUPP_CHARGER_STATUS_BQ25756E_ERROR_BATTERY_OV = 5,
    SUPP_CHARGER_STATUS_BQ25756E_ERROR_OVER_TEMPERATURE = 6,
} supp_charger_status_bq25756e_error_e;

typedef enum {
    SUPP_CHARGER_STATUS_BQ25756E_WATCHDOG_NOT_OK = 0,
    SUPP_CHARGER_STATUS_BQ25756E_WATCHDOG_OK = 1,
} supp_charger_status_bq25756e_watchdog_e;

typedef enum {
    PDU_STATUS_ARR_HSS_CHANNEL_IDX_VCU = 0,
    PDU_STATUS_ARR_HSS_CHANNEL_IDX_DASHBOARD = 1,
    PDU_STATUS_ARR_HSS_CHANNEL_IDX_HORN = 2,
    PDU_STATUS_ARR_HSS_CHANNEL_IDX_LIGHTS = 3,
    PDU_STATUS_ARR_HSS_CHANNEL_IDX_PI_DISPLAY = 4,
    PDU_STATUS_ARR_HSS_CHANNEL_IDX_PEDALS = 5,
    PDU_STATUS_ARR_HSS_CHANNEL_IDX_CAMERAS = 6,
    PDU_STATUS_ARR_HSS_CHANNEL_IDX_UNASSIGNED_0 = 7,
    PDU_STATUS_ARR_HSS_CHANNEL_IDX_BATTERY = 8,
    PDU_STATUS_ARR_HSS_CHANNEL_IDX_MPPTS = 9,
    PDU_STATUS_ARR_HSS_CHANNEL_IDX_MOTOR_CONTROLLER = 10,
    PDU_STATUS_ARR_HSS_CHANNEL_IDX_TELEMETRY_DATA_ACQ = 11,
    PDU_STATUS_ARR_HSS_CHANNEL_IDX_PUMP = 12,
    PDU_STATUS_ARR_HSS_CHANNEL_IDX_UNASSIGNED_1 = 13,
    PDU_STATUS_ARR_HSS_CHANNEL_IDX_UNASSIGNED_2 = 14,
    PDU_STATUS_ARR_HSS_CHANNEL_IDX_PDE_FANS = 15,
} pdu_status_arr_hss_channel_idx_e;

typedef enum {
    PDU_STATUS_ARR_HSS_FAULT_OK = 0,
    PDU_STATUS_ARR_HSS_FAULT_FAULT = 1,
} pdu_status_arr_hss_fault_e;

typedef enum {
    PDU_STATUS_ARR_HSS_ENABLED_DISABLED = 0,
    PDU_STATUS_ARR_HSS_ENABLED_ENABLED = 1,
} pdu_status_arr_hss_enabled_e;

typedef enum {
    PDU_SET_SWITCH_ARR_HSS_CHANNEL_IDX_VCU = 0,
    PDU_SET_SWITCH_ARR_HSS_CHANNEL_IDX_DASHBOARD = 1,
    PDU_SET_SWITCH_ARR_HSS_CHANNEL_IDX_HORN = 2,
    PDU_SET_SWITCH_ARR_HSS_CHANNEL_IDX_LIGHTS = 3,
    PDU_SET_SWITCH_ARR_HSS_CHANNEL_IDX_PI_DISPLAY = 4,
    PDU_SET_SWITCH_ARR_HSS_CHANNEL_IDX_PEDALS = 5,
    PDU_SET_SWITCH_ARR_HSS_CHANNEL_IDX_CAMERAS = 6,
    PDU_SET_SWITCH_ARR_HSS_CHANNEL_IDX_UNASSIGNED_0 = 7,
    PDU_SET_SWITCH_ARR_HSS_CHANNEL_IDX_BATTERY = 8,
    PDU_SET_SWITCH_ARR_HSS_CHANNEL_IDX_MPPTS = 9,
    PDU_SET_SWITCH_ARR_HSS_CHANNEL_IDX_MOTOR_CONTROLLER = 10,
    PDU_SET_SWITCH_ARR_HSS_CHANNEL_IDX_TELEMETRY_DATA_ACQ = 11,
    PDU_SET_SWITCH_ARR_HSS_CHANNEL_IDX_PUMP = 12,
    PDU_SET_SWITCH_ARR_HSS_CHANNEL_IDX_UNASSIGNED_1 = 13,
    PDU_SET_SWITCH_ARR_HSS_CHANNEL_IDX_UNASSIGNED_2 = 14,
    PDU_SET_SWITCH_ARR_HSS_CHANNEL_IDX_PDE_FANS = 15,
} pdu_set_switch_arr_hss_channel_idx_e;

typedef enum {
    PDU_SET_SWITCH_ARR_HSS_SETSWITCH_DO_NOTHING = 0,
    PDU_SET_SWITCH_ARR_HSS_SETSWITCH_TOGGLE_ON = 1,
    PDU_SET_SWITCH_ARR_HSS_SETSWITCH_TOGGLE_OFF = 2,
} pdu_set_switch_arr_hss_setswitch_e;

typedef enum {
    PDU_SET_CURRENT_LIMIT_ARR_HSS_CHANNEL_IDX_VCU = 0,
    PDU_SET_CURRENT_LIMIT_ARR_HSS_CHANNEL_IDX_DASHBOARD = 1,
    PDU_SET_CURRENT_LIMIT_ARR_HSS_CHANNEL_IDX_HORN = 2,
    PDU_SET_CURRENT_LIMIT_ARR_HSS_CHANNEL_IDX_LIGHTS = 3,
    PDU_SET_CURRENT_LIMIT_ARR_HSS_CHANNEL_IDX_PI_DISPLAY = 4,
    PDU_SET_CURRENT_LIMIT_ARR_HSS_CHANNEL_IDX_PEDALS = 5,
    PDU_SET_CURRENT_LIMIT_ARR_HSS_CHANNEL_IDX_CAMERAS = 6,
    PDU_SET_CURRENT_LIMIT_ARR_HSS_CHANNEL_IDX_UNASSIGNED_0 = 7,
    PDU_SET_CURRENT_LIMIT_ARR_HSS_CHANNEL_IDX_BATTERY = 8,
    PDU_SET_CURRENT_LIMIT_ARR_HSS_CHANNEL_IDX_MPPTS = 9,
    PDU_SET_CURRENT_LIMIT_ARR_HSS_CHANNEL_IDX_MOTOR_CONTROLLER = 10,
    PDU_SET_CURRENT_LIMIT_ARR_HSS_CHANNEL_IDX_TELEMETRY_DATA_ACQ = 11,
    PDU_SET_CURRENT_LIMIT_ARR_HSS_CHANNEL_IDX_PUMP = 12,
    PDU_SET_CURRENT_LIMIT_ARR_HSS_CHANNEL_IDX_UNASSIGNED_1 = 13,
    PDU_SET_CURRENT_LIMIT_ARR_HSS_CHANNEL_IDX_UNASSIGNED_2 = 14,
    PDU_SET_CURRENT_LIMIT_ARR_HSS_CHANNEL_IDX_PDE_FANS = 15,
} pdu_set_current_limit_arr_hss_channel_idx_e;

typedef enum {
    MC_STATUS_MC_LIMIT_OUTPUTVOLTAGEPWM_OK = 0,
    MC_STATUS_MC_LIMIT_OUTPUTVOLTAGEPWM_LIMIT = 1,
} mc_status_mc_limit_outputvoltagepwm_e;

typedef enum {
    MC_STATUS_MC_LIMIT_MOTORCURRENT_OK = 0,
    MC_STATUS_MC_LIMIT_MOTORCURRENT_LIMIT = 1,
} mc_status_mc_limit_motorcurrent_e;

typedef enum {
    MC_STATUS_MC_LIMIT_VELOCITY_OK = 0,
    MC_STATUS_MC_LIMIT_VELOCITY_LIMIT = 1,
} mc_status_mc_limit_velocity_e;

typedef enum {
    MC_STATUS_MC_LIMIT_BUSCURRENT_OK = 0,
    MC_STATUS_MC_LIMIT_BUSCURRENT_LIMIT = 1,
} mc_status_mc_limit_buscurrent_e;

typedef enum {
    MC_STATUS_MC_LIMIT_BUSVOLTAGEUPPER_OK = 0,
    MC_STATUS_MC_LIMIT_BUSVOLTAGEUPPER_LIMIT = 1,
} mc_status_mc_limit_busvoltageupper_e;

typedef enum {
    MC_STATUS_MC_LIMIT_BUSVOLTAGELOWER_OK = 0,
    MC_STATUS_MC_LIMIT_BUSVOLTAGELOWER_LIMIT = 1,
} mc_status_mc_limit_busvoltagelower_e;

typedef enum {
    MC_STATUS_MC_LIMIT_MOTORTEMP_OK = 0,
    MC_STATUS_MC_LIMIT_MOTORTEMP_LIMIT = 1,
} mc_status_mc_limit_motortemp_e;

typedef enum {
    MC_STATUS_MC_LIMIT_RESERVED_OK = 0,
    MC_STATUS_MC_LIMIT_RESERVED_LIMIT = 1,
} mc_status_mc_limit_reserved_e;

typedef enum {
    MC_STATUS_MC_FAULT_HARDWAREOVERCURRENT_OK = 0,
    MC_STATUS_MC_FAULT_HARDWAREOVERCURRENT_FAULT = 1,
} mc_status_mc_fault_hardwareovercurrent_e;

typedef enum {
    MC_STATUS_MC_FAULT_SOFTWAREOVERCURRENT_OK = 0,
    MC_STATUS_MC_FAULT_SOFTWAREOVERCURRENT_FAULT = 1,
} mc_status_mc_fault_softwareovercurrent_e;

typedef enum {
    MC_STATUS_MC_FAULT_DCBUSOVERVOLTAGE_OK = 0,
    MC_STATUS_MC_FAULT_DCBUSOVERVOLTAGE_FAULT = 1,
} mc_status_mc_fault_dcbusovervoltage_e;

typedef enum {
    MC_STATUS_MC_FAULT_BADMOTORPOSITIONHALLSEQ_OK = 0,
    MC_STATUS_MC_FAULT_BADMOTORPOSITIONHALLSEQ_FAULT = 1,
} mc_status_mc_fault_badmotorpositionhallseq_e;

typedef enum {
    MC_STATUS_MC_FAULT_WATCHDOGCAUSEDLASTRESET_OK = 0,
    MC_STATUS_MC_FAULT_WATCHDOGCAUSEDLASTRESET_FAULT = 1,
} mc_status_mc_fault_watchdogcausedlastreset_e;

typedef enum {
    MC_STATUS_MC_FAULT_CONFIGREAD_OK = 0,
    MC_STATUS_MC_FAULT_CONFIGREAD_FAULT = 1,
} mc_status_mc_fault_configread_e;

typedef enum {
    MC_STATUS_MC_FAULT_15VRAILUNDERVOLTAGE_OK = 0,
    MC_STATUS_MC_FAULT_15VRAILUNDERVOLTAGE_FAULT = 1,
} mc_status_mc_fault_15vrailundervoltage_e;

typedef enum {
    MC_STATUS_MC_FAULT_DESATURATIONFAULT_OK = 0,
    MC_STATUS_MC_FAULT_DESATURATIONFAULT_FAULT = 1,
} mc_status_mc_fault_desaturationfault_e;

typedef enum {
    MC_STATUS_MC_FAULT_MOTOROVERSPEED_OK = 0,
    MC_STATUS_MC_FAULT_MOTOROVERSPEED_FAULT = 1,
} mc_status_mc_fault_motoroverspeed_e;

typedef enum {
    MC_STATUS_MC_FAULT_RESERVED_OK = 0,
    MC_STATUS_MC_FAULT_RESERVED_FAULT = 1,
} mc_status_mc_fault_reserved_e;

typedef enum {
    PUMP_STATUS_PUMP_FAULT_OK = 0,
    PUMP_STATUS_PUMP_FAULT_FAULT = 1,
} pump_status_pump_fault_e;

typedef enum {
    LV_CARRIER_STATUS_LTC4421_HVDCDC_SELECTED__ = 0,
    LV_CARRIER_STATUS_LTC4421_HVDCDC_SELECTED_SELECTED = 1,
} lv_carrier_status_ltc4421_hvdcdc_selected_e;

typedef enum {
    LV_CARRIER_STATUS_LTC4421_HVDCDC_FAULT_OK = 0,
    LV_CARRIER_STATUS_LTC4421_HVDCDC_FAULT_FAULT = 1,
} lv_carrier_status_ltc4421_hvdcdc_fault_e;

typedef enum {
    LV_CARRIER_STATUS_LTC4421_HVDCDC_VALID_NOT_OK = 0,
    LV_CARRIER_STATUS_LTC4421_HVDCDC_VALID_OK = 1,
} lv_carrier_status_ltc4421_hvdcdc_valid_e;

typedef enum {
    LV_CARRIER_STATUS_LTC4421_SUPPBATT_SELECTED__ = 0,
    LV_CARRIER_STATUS_LTC4421_SUPPBATT_SELECTED_SELECTED = 1,
} lv_carrier_status_ltc4421_suppbatt_selected_e;

typedef enum {
    LV_CARRIER_STATUS_LTC4421_SUPPBATT_FAULT_OK = 0,
    LV_CARRIER_STATUS_LTC4421_SUPPBATT_FAULT_FAULT = 1,
} lv_carrier_status_ltc4421_suppbatt_fault_e;

typedef enum {
    LV_CARRIER_STATUS_LTC4421_SUPPBATT_VALID_NOT_OK = 0,
    LV_CARRIER_STATUS_LTC4421_SUPPBATT_VALID_OK = 1,
} lv_carrier_status_ltc4421_suppbatt_valid_e;

typedef enum {
    LV_CARRIER_STATUS_LV_EN_SUPPLEMENTALBATTERY_DISABLED = 0,
    LV_CARRIER_STATUS_LV_EN_SUPPLEMENTALBATTERY_ENABLED = 1,
} lv_carrier_status_lv_en_supplementalbattery_e;

typedef enum {
    LV_CARRIER_STATUS_LV_EN_POWERSUPPLY_DISABLED = 0,
    LV_CARRIER_STATUS_LV_EN_POWERSUPPLY_ENABLED = 1,
} lv_carrier_status_lv_en_powersupply_e;

typedef enum {
    LIGHTING_COMMAND_LIGHTING_SET_HEADLIGHTS_OFF = 0,
    LIGHTING_COMMAND_LIGHTING_SET_HEADLIGHTS_ON = 1,
} lighting_command_lighting_set_headlights_e;

typedef enum {
    LIGHTING_COMMAND_LIGHTING_SET_LEFT_INDICATOR_OFF = 0,
    LIGHTING_COMMAND_LIGHTING_SET_LEFT_INDICATOR_ON = 1,
} lighting_command_lighting_set_left_indicator_e;

typedef enum {
    LIGHTING_COMMAND_LIGHTING_SET_RIGHT_INDICATOR_OFF = 0,
    LIGHTING_COMMAND_LIGHTING_SET_RIGHT_INDICATOR_ON = 1,
} lighting_command_lighting_set_right_indicator_e;

typedef enum {
    LIGHTING_COMMAND_LIGHTING_SET_BRAKE_OFF = 0,
    LIGHTING_COMMAND_LIGHTING_SET_BRAKE_ON = 1,
} lighting_command_lighting_set_brake_e;

typedef enum {
    LIGHTING_COMMAND_LIGHTING_SET_BPS_STROBE_OFF = 0,
    LIGHTING_COMMAND_LIGHTING_SET_BPS_STROBE_ON = 1,
} lighting_command_lighting_set_bps_strobe_e;

typedef enum {
    LIGHTING_COMMAND_LIGHTING_SET_CUSTOM_MODE_OFF = 0,
    LIGHTING_COMMAND_LIGHTING_SET_CUSTOM_MODE_MODE_1_ACTIVE = 1,
    LIGHTING_COMMAND_LIGHTING_SET_CUSTOM_MODE_MODE_2_ACTIVE = 2,
    LIGHTING_COMMAND_LIGHTING_SET_CUSTOM_MODE_MODE_3_ACTIVE = 3,
} lighting_command_lighting_set_custom_mode_e;

typedef enum {
    LIGHTING_FRONT_STATUS_LIGHTING_BOARD_FAULT_OK = 0,
    LIGHTING_FRONT_STATUS_LIGHTING_BOARD_FAULT_ADDR_LED_UNDERCURRENT = 1,
    LIGHTING_FRONT_STATUS_LIGHTING_BOARD_FAULT_LED0_UNDERCURRENT = 2,
    LIGHTING_FRONT_STATUS_LIGHTING_BOARD_FAULT_LED1_UNDERCURRENT = 3,
    LIGHTING_FRONT_STATUS_LIGHTING_BOARD_FAULT_ADDR_LED_OVERCURRENT = 4,
    LIGHTING_FRONT_STATUS_LIGHTING_BOARD_FAULT_LED0_OVERCURRENT = 5,
    LIGHTING_FRONT_STATUS_LIGHTING_BOARD_FAULT_LED1_OVERCURRENT = 6,
    LIGHTING_FRONT_STATUS_LIGHTING_BOARD_FAULT_LIGHT_COMMAND_WATCHDOG = 7,
    LIGHTING_FRONT_STATUS_LIGHTING_BOARD_FAULT_WATCHDOG = 8,
} lighting_front_status_lighting_board_fault_e;

typedef enum {
    LIGHTING_FRONT_STATUS_LIGHT_HEADLIGHT_OFF = 0,
    LIGHTING_FRONT_STATUS_LIGHT_HEADLIGHT_ON = 1,
} lighting_front_status_light_headlight_e;

typedef enum {
    LIGHTING_FRONT_STATUS_LIGHT_LEFT_INDICATOR_OFF = 0,
    LIGHTING_FRONT_STATUS_LIGHT_LEFT_INDICATOR_ON = 1,
} lighting_front_status_light_left_indicator_e;

typedef enum {
    LIGHTING_FRONT_STATUS_LIGHT_RIGHT_INDICATOR_OFF = 0,
    LIGHTING_FRONT_STATUS_LIGHT_RIGHT_INDICATOR_ON = 1,
} lighting_front_status_light_right_indicator_e;

typedef enum {
    LIGHTING_FRONT_STATUS_LIGHT_BPS_STROBE_OFF = 0,
    LIGHTING_FRONT_STATUS_LIGHT_BPS_STROBE_ON = 1,
} lighting_front_status_light_bps_strobe_e;

typedef enum {
    LIGHTING_FRONT_STATUS_LIGHT_BRAKELIGHT_OFF = 0,
    LIGHTING_FRONT_STATUS_LIGHT_BRAKELIGHT_ON = 1,
} lighting_front_status_light_brakelight_e;

typedef enum {
    LIGHTING_FRONT_STATUS_LIGHT_CUSTOMMODE_OFF = 0,
    LIGHTING_FRONT_STATUS_LIGHT_CUSTOMMODE_ON = 1,
} lighting_front_status_light_custommode_e;

typedef enum {
    LIGHTING_LEFT_STATUS_LIGHTING_BOARD_FAULT_OK = 0,
    LIGHTING_LEFT_STATUS_LIGHTING_BOARD_FAULT_ADDR_LED_UNDERCURRENT = 1,
    LIGHTING_LEFT_STATUS_LIGHTING_BOARD_FAULT_LED0_UNDERCURRENT = 2,
    LIGHTING_LEFT_STATUS_LIGHTING_BOARD_FAULT_LED1_UNDERCURRENT = 3,
    LIGHTING_LEFT_STATUS_LIGHTING_BOARD_FAULT_ADDR_LED_OVERCURRENT = 4,
    LIGHTING_LEFT_STATUS_LIGHTING_BOARD_FAULT_LED0_OVERCURRENT = 5,
    LIGHTING_LEFT_STATUS_LIGHTING_BOARD_FAULT_LED1_OVERCURRENT = 6,
    LIGHTING_LEFT_STATUS_LIGHTING_BOARD_FAULT_LIGHT_COMMAND_WATCHDOG = 7,
    LIGHTING_LEFT_STATUS_LIGHTING_BOARD_FAULT_WATCHDOG = 8,
} lighting_left_status_lighting_board_fault_e;

typedef enum {
    LIGHTING_LEFT_STATUS_LIGHT_HEADLIGHT_OFF = 0,
    LIGHTING_LEFT_STATUS_LIGHT_HEADLIGHT_ON = 1,
} lighting_left_status_light_headlight_e;

typedef enum {
    LIGHTING_LEFT_STATUS_LIGHT_LEFT_INDICATOR_OFF = 0,
    LIGHTING_LEFT_STATUS_LIGHT_LEFT_INDICATOR_ON = 1,
} lighting_left_status_light_left_indicator_e;

typedef enum {
    LIGHTING_LEFT_STATUS_LIGHT_RIGHT_INDICATOR_OFF = 0,
    LIGHTING_LEFT_STATUS_LIGHT_RIGHT_INDICATOR_ON = 1,
} lighting_left_status_light_right_indicator_e;

typedef enum {
    LIGHTING_LEFT_STATUS_LIGHT_BPS_STROBE_OFF = 0,
    LIGHTING_LEFT_STATUS_LIGHT_BPS_STROBE_ON = 1,
} lighting_left_status_light_bps_strobe_e;

typedef enum {
    LIGHTING_LEFT_STATUS_LIGHT_BRAKELIGHT_OFF = 0,
    LIGHTING_LEFT_STATUS_LIGHT_BRAKELIGHT_ON = 1,
} lighting_left_status_light_brakelight_e;

typedef enum {
    LIGHTING_LEFT_STATUS_LIGHT_CUSTOMMODE_OFF = 0,
    LIGHTING_LEFT_STATUS_LIGHT_CUSTOMMODE_ON = 1,
} lighting_left_status_light_custommode_e;

typedef enum {
    LIGHTING_REAR_STATUS_LIGHTING_BOARD_FAULT_OK = 0,
    LIGHTING_REAR_STATUS_LIGHTING_BOARD_FAULT_ADDR_LED_UNDERCURRENT = 1,
    LIGHTING_REAR_STATUS_LIGHTING_BOARD_FAULT_LED0_UNDERCURRENT = 2,
    LIGHTING_REAR_STATUS_LIGHTING_BOARD_FAULT_LED1_UNDERCURRENT = 3,
    LIGHTING_REAR_STATUS_LIGHTING_BOARD_FAULT_ADDR_LED_OVERCURRENT = 4,
    LIGHTING_REAR_STATUS_LIGHTING_BOARD_FAULT_LED0_OVERCURRENT = 5,
    LIGHTING_REAR_STATUS_LIGHTING_BOARD_FAULT_LED1_OVERCURRENT = 6,
    LIGHTING_REAR_STATUS_LIGHTING_BOARD_FAULT_LIGHT_COMMAND_WATCHDOG = 7,
    LIGHTING_REAR_STATUS_LIGHTING_BOARD_FAULT_WATCHDOG = 8,
} lighting_rear_status_lighting_board_fault_e;

typedef enum {
    LIGHTING_REAR_STATUS_LIGHT_HEADLIGHT_OFF = 0,
    LIGHTING_REAR_STATUS_LIGHT_HEADLIGHT_ON = 1,
} lighting_rear_status_light_headlight_e;

typedef enum {
    LIGHTING_REAR_STATUS_LIGHT_LEFT_INDICATOR_OFF = 0,
    LIGHTING_REAR_STATUS_LIGHT_LEFT_INDICATOR_ON = 1,
} lighting_rear_status_light_left_indicator_e;

typedef enum {
    LIGHTING_REAR_STATUS_LIGHT_RIGHT_INDICATOR_OFF = 0,
    LIGHTING_REAR_STATUS_LIGHT_RIGHT_INDICATOR_ON = 1,
} lighting_rear_status_light_right_indicator_e;

typedef enum {
    LIGHTING_REAR_STATUS_LIGHT_BPS_STROBE_OFF = 0,
    LIGHTING_REAR_STATUS_LIGHT_BPS_STROBE_ON = 1,
} lighting_rear_status_light_bps_strobe_e;

typedef enum {
    LIGHTING_REAR_STATUS_LIGHT_BRAKELIGHT_OFF = 0,
    LIGHTING_REAR_STATUS_LIGHT_BRAKELIGHT_ON = 1,
} lighting_rear_status_light_brakelight_e;

typedef enum {
    LIGHTING_REAR_STATUS_LIGHT_CUSTOMMODE_OFF = 0,
    LIGHTING_REAR_STATUS_LIGHT_CUSTOMMODE_ON = 1,
} lighting_rear_status_light_custommode_e;

typedef enum {
    LIGHTING_RIGHT_STATUS_LIGHTING_BOARD_FAULT_OK = 0,
    LIGHTING_RIGHT_STATUS_LIGHTING_BOARD_FAULT_ADDR_LED_UNDERCURRENT = 1,
    LIGHTING_RIGHT_STATUS_LIGHTING_BOARD_FAULT_LED0_UNDERCURRENT = 2,
    LIGHTING_RIGHT_STATUS_LIGHTING_BOARD_FAULT_LED1_UNDERCURRENT = 3,
    LIGHTING_RIGHT_STATUS_LIGHTING_BOARD_FAULT_ADDR_LED_OVERCURRENT = 4,
    LIGHTING_RIGHT_STATUS_LIGHTING_BOARD_FAULT_LED0_OVERCURRENT = 5,
    LIGHTING_RIGHT_STATUS_LIGHTING_BOARD_FAULT_LED1_OVERCURRENT = 6,
    LIGHTING_RIGHT_STATUS_LIGHTING_BOARD_FAULT_LIGHT_COMMAND_WATCHDOG = 7,
    LIGHTING_RIGHT_STATUS_LIGHTING_BOARD_FAULT_WATCHDOG = 8,
} lighting_right_status_lighting_board_fault_e;

typedef enum {
    LIGHTING_RIGHT_STATUS_LIGHT_HEADLIGHT_OFF = 0,
    LIGHTING_RIGHT_STATUS_LIGHT_HEADLIGHT_ON = 1,
} lighting_right_status_light_headlight_e;

typedef enum {
    LIGHTING_RIGHT_STATUS_LIGHT_LEFT_INDICATOR_OFF = 0,
    LIGHTING_RIGHT_STATUS_LIGHT_LEFT_INDICATOR_ON = 1,
} lighting_right_status_light_left_indicator_e;

typedef enum {
    LIGHTING_RIGHT_STATUS_LIGHT_RIGHT_INDICATOR_OFF = 0,
    LIGHTING_RIGHT_STATUS_LIGHT_RIGHT_INDICATOR_ON = 1,
} lighting_right_status_light_right_indicator_e;

typedef enum {
    LIGHTING_RIGHT_STATUS_LIGHT_BPS_STROBE_OFF = 0,
    LIGHTING_RIGHT_STATUS_LIGHT_BPS_STROBE_ON = 1,
} lighting_right_status_light_bps_strobe_e;

typedef enum {
    LIGHTING_RIGHT_STATUS_LIGHT_BRAKELIGHT_OFF = 0,
    LIGHTING_RIGHT_STATUS_LIGHT_BRAKELIGHT_ON = 1,
} lighting_right_status_light_brakelight_e;

typedef enum {
    LIGHTING_RIGHT_STATUS_LIGHT_CUSTOMMODE_OFF = 0,
    LIGHTING_RIGHT_STATUS_LIGHT_CUSTOMMODE_ON = 1,
} lighting_right_status_light_custommode_e;

typedef enum {
    LIGHTING_CANOPY_STATUS_LIGHTING_BOARD_FAULT_OK = 0,
    LIGHTING_CANOPY_STATUS_LIGHTING_BOARD_FAULT_ADDR_LED_UNDERCURRENT = 1,
    LIGHTING_CANOPY_STATUS_LIGHTING_BOARD_FAULT_LED0_UNDERCURRENT = 2,
    LIGHTING_CANOPY_STATUS_LIGHTING_BOARD_FAULT_LED1_UNDERCURRENT = 3,
    LIGHTING_CANOPY_STATUS_LIGHTING_BOARD_FAULT_ADDR_LED_OVERCURRENT = 4,
    LIGHTING_CANOPY_STATUS_LIGHTING_BOARD_FAULT_LED0_OVERCURRENT = 5,
    LIGHTING_CANOPY_STATUS_LIGHTING_BOARD_FAULT_LED1_OVERCURRENT = 6,
    LIGHTING_CANOPY_STATUS_LIGHTING_BOARD_FAULT_LIGHT_COMMAND_WATCHDOG = 7,
    LIGHTING_CANOPY_STATUS_LIGHTING_BOARD_FAULT_WATCHDOG = 8,
} lighting_canopy_status_lighting_board_fault_e;

typedef enum {
    LIGHTING_CANOPY_STATUS_LIGHT_HEADLIGHT_OFF = 0,
    LIGHTING_CANOPY_STATUS_LIGHT_HEADLIGHT_ON = 1,
} lighting_canopy_status_light_headlight_e;

typedef enum {
    LIGHTING_CANOPY_STATUS_LIGHT_LEFT_INDICATOR_OFF = 0,
    LIGHTING_CANOPY_STATUS_LIGHT_LEFT_INDICATOR_ON = 1,
} lighting_canopy_status_light_left_indicator_e;

typedef enum {
    LIGHTING_CANOPY_STATUS_LIGHT_RIGHT_INDICATOR_OFF = 0,
    LIGHTING_CANOPY_STATUS_LIGHT_RIGHT_INDICATOR_ON = 1,
} lighting_canopy_status_light_right_indicator_e;

typedef enum {
    LIGHTING_CANOPY_STATUS_LIGHT_BPS_STROBE_OFF = 0,
    LIGHTING_CANOPY_STATUS_LIGHT_BPS_STROBE_ON = 1,
} lighting_canopy_status_light_bps_strobe_e;

typedef enum {
    LIGHTING_CANOPY_STATUS_LIGHT_BRAKELIGHT_OFF = 0,
    LIGHTING_CANOPY_STATUS_LIGHT_BRAKELIGHT_ON = 1,
} lighting_canopy_status_light_brakelight_e;

typedef enum {
    LIGHTING_CANOPY_STATUS_LIGHT_CUSTOMMODE_OFF = 0,
    LIGHTING_CANOPY_STATUS_LIGHT_CUSTOMMODE_ON = 1,
} lighting_canopy_status_light_custommode_e;

typedef enum {
    DISPLAY_STATUS_CAMERA_STATUS_BACKUP_NOT_OK = 0,
    DISPLAY_STATUS_CAMERA_STATUS_BACKUP_OK = 1,
} display_status_camera_status_backup_e;

typedef enum {
    DISPLAY_STATUS_CAMERA_STATUS_LEFT_NOT_OK = 0,
    DISPLAY_STATUS_CAMERA_STATUS_LEFT_OK = 1,
} display_status_camera_status_left_e;

typedef enum {
    DISPLAY_STATUS_CAMERA_STATUS_RIGHT_NOT_OK = 0,
    DISPLAY_STATUS_CAMERA_STATUS_RIGHT_OK = 1,
} display_status_camera_status_right_e;

typedef enum {
    SET_MOTOR_CMD_SRC_MOTOR_COMMAND_SOURCE_VCU = 0,
    SET_MOTOR_CMD_SRC_MOTOR_COMMAND_SOURCE_TRITIUM_EXTERNAL = 1,
} set_motor_cmd_src_motor_command_source_e;

typedef enum {
    LWS_CONFIG_LWS_CCW_SETS_THE_SIGNAL_LWS_ANGLE_TO_0_ = 3,
    LWS_CONFIG_LWS_CCW_RESETS_CALIBRATION_STATUS = 5,
} lws_config_lws_ccw_e;

typedef enum {
    ELCON_CONTROL_MUX_ELCON_MUXPAGE_PAGE_1 = 1,
    ELCON_CONTROL_MUX_ELCON_MUXPAGE_PAGE_2 = 2,
    ELCON_CONTROL_MUX_ELCON_MUXPAGE_PAGE_3 = 3,
    ELCON_CONTROL_MUX_ELCON_MUXPAGE_PAGE_4 = 4,
    ELCON_CONTROL_MUX_ELCON_MUXPAGE_PAGE_5 = 5,
} elcon_control_mux_elcon_muxpage_e;

typedef enum {
    ELCON_CCS_STATUS_ELCON_HW_FAULT_OK = 0,
    ELCON_CCS_STATUS_ELCON_HW_FAULT_FAULT = 1,
} elcon_ccs_status_elcon_hw_fault_e;

typedef enum {
    ELCON_CCS_STATUS_ELCON_OVER_TEMPERATURE_OK = 0,
    ELCON_CCS_STATUS_ELCON_OVER_TEMPERATURE_FAULT = 1,
} elcon_ccs_status_elcon_over_temperature_e;

typedef enum {
    ELCON_CCS_STATUS_ELCON_INPUT_VOL_ERROR_OK = 0,
    ELCON_CCS_STATUS_ELCON_INPUT_VOL_ERROR_FAULT = 1,
} elcon_ccs_status_elcon_input_vol_error_e;

typedef enum {
    ELCON_CCS_STATUS_ELCON_START_STATE_NOT_OK = 0,
    ELCON_CCS_STATUS_ELCON_START_STATE_OK = 1,
} elcon_ccs_status_elcon_start_state_e;

typedef enum {
    ELCON_CCS_STATUS_ELCON_CMD_TIMEOUT_NOT_OK = 0,
    ELCON_CCS_STATUS_ELCON_CMD_TIMEOUT_OK = 1,
} elcon_ccs_status_elcon_cmd_timeout_e;

/* ================= Message Structs ================= */

typedef struct {
    uint8_t BPS_Fault;
    uint8_t BPS_Charge_OK;
    uint8_t BPS_Regen_OK;
    uint8_t HV_Plus_Contactor_State;
    uint8_t HV_Minus_Contactor_State;
    uint8_t Array_Contactor_State;
    uint8_t Array_Precharge_Contactor_State;
    uint32_t Main_Battery_Voltage;
    int16_t Main_Battery_Avg_Temperature;
    uint8_t BPS_Segment0_Status;
    uint8_t BPS_Segment1_Status;
    uint8_t BPS_Segment2_Status;
    uint8_t BPS_Segment3_Status;
    uint8_t BPS_Segment4_Status;
    uint8_t BPS_Segment5_Status;
    uint8_t BPS_Segment6_Status;
    uint8_t BPS_Segment7_Status;
} bps_status_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    uint16_t BPS_Voltage_Tap_Data;
    uint8_t BPS_Voltage_Tap_Fault;
} bps_vt0_voltage_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    uint16_t BPS_Voltage_Tap_Data;
    uint8_t BPS_Voltage_Tap_Fault;
} bps_vt1_voltage_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    uint16_t BPS_Voltage_Tap_Data;
    uint8_t BPS_Voltage_Tap_Fault;
} bps_vt2_voltage_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    uint16_t BPS_Voltage_Tap_Data;
    uint8_t BPS_Voltage_Tap_Fault;
} bps_vt3_voltage_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    uint16_t BPS_Voltage_Tap_Data;
    uint8_t BPS_Voltage_Tap_Fault;
} bps_vt4_voltage_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    uint16_t BPS_Voltage_Tap_Data;
    uint8_t BPS_Voltage_Tap_Fault;
} bps_vt5_voltage_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    uint16_t BPS_Voltage_Tap_Data;
    uint8_t BPS_Voltage_Tap_Fault;
} bps_vt6_voltage_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    uint16_t BPS_Voltage_Tap_Data;
    uint8_t BPS_Voltage_Tap_Fault;
} bps_vt7_voltage_arr_t;

typedef struct {
    uint8_t BPS_Amperes_Fault;
    int32_t Main_Battery_Current;
    uint8_t FrameID_Amperes;
} bps_pack_current_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    uint16_t BPS_Voltage_Tap_Data;
    uint8_t BPS_Voltage_Tap_Fault;
    uint16_t BPS_Voltage_Tap_Age;
} bps_voltage_aggregate_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    int32_t BPS_Temperature_Tap_Data;
    uint8_t BPS_Temperature_Tap_Fault;
    uint16_t BPS_Temperature_Tap_Age;
    uint8_t FrameID_BPS_Temperature;
} bps_temperature_aggregate_arr_t;

typedef struct {
    uint16_t Elcon_VOL_OUT;
    uint16_t Elcon_CUR_OUT;
    uint8_t Elcon_HW_FAULT;
    uint8_t Elcon_OVER_TEMPERATURE;
    uint8_t Elcon_INPUT_VOL_ERROR;
    uint8_t Elcon_START_STATE;
    uint8_t Elcon_CMD_TIMEOUT;
    uint8_t Elcon_Watchdog;
} chargerinterface_status_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    int32_t BPS_Temperature_Tap_Data;
    uint8_t BPS_Temperature_Tap_Fault;
    uint16_t BPS_Temperature_Tap_ADC;
} bps_vt0_temperature_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    int32_t BPS_Temperature_Tap_Data;
    uint8_t BPS_Temperature_Tap_Fault;
    uint16_t BPS_Temperature_Tap_ADC;
} bps_vt1_temperature_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    int32_t BPS_Temperature_Tap_Data;
    uint8_t BPS_Temperature_Tap_Fault;
    uint16_t BPS_Temperature_Tap_ADC;
} bps_vt2_temperature_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    int32_t BPS_Temperature_Tap_Data;
    uint8_t BPS_Temperature_Tap_Fault;
    uint16_t BPS_Temperature_Tap_ADC;
} bps_vt3_temperature_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    int32_t BPS_Temperature_Tap_Data;
    uint8_t BPS_Temperature_Tap_Fault;
    uint16_t BPS_Temperature_Tap_ADC;
} bps_vt4_temperature_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    int32_t BPS_Temperature_Tap_Data;
    uint8_t BPS_Temperature_Tap_Fault;
    uint16_t BPS_Temperature_Tap_ADC;
} bps_vt5_temperature_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    int32_t BPS_Temperature_Tap_Data;
    uint8_t BPS_Temperature_Tap_Fault;
    uint16_t BPS_Temperature_Tap_ADC;
} bps_vt6_temperature_arr_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    int32_t BPS_Temperature_Tap_Data;
    uint8_t BPS_Temperature_Tap_Fault;
    uint16_t BPS_Temperature_Tap_ADC;
} bps_vt7_temperature_arr_t;

typedef struct {
    uint8_t VCU_FSM_State;
    uint8_t Motor_Ready;
    uint8_t Motor_Precharge_Contactor_State;
    uint8_t Motor_Contactor_State;
    uint8_t VCU_Driver_Input_Watchdog;
    uint8_t VCU_Pedals_Watchdog;
    uint8_t VCU_BPS_Watchdog;
    uint8_t VCU_Steering_Angle_Watchdog;
    uint8_t VCU_BPS_FAULT_DETECTED;
    uint8_t VCU_CONTROLS_FAULT_DETECTED;
    uint8_t VCU_MTR_FAULT_DETECTED;
    uint8_t VCU_PEDALS_FAULT_DETECTED;
    uint8_t VCU_STEERING_FAULT_DETECTED;
    uint8_t VCU_MotorCommandSource;
    uint8_t VCU_Regen_Active;
    uint8_t VCU_Regen_OK;
    uint8_t VCU_MTR_PCHG_TIMEOUT;
    uint8_t VCU_MTR_PCHG_CONT_TIMEOUT;
    uint8_t VCU_MTR_PCHG_CONT_MISMATCH;
    uint8_t VCU_MTR_CONT_MISMATCH;
    uint8_t VCU_MTR_CONT_TIMEOUT;
    uint8_t VCU_PCHG_OV;
    uint8_t VCU_PCHG_UV;
    uint8_t VCU_MTR_OV;
    uint8_t VCU_MTR_UV;
    uint8_t VCU_OTHER_FAULT;
    uint8_t VCU_MTR_DIR_CHANGE_LOCKOUT;
    uint8_t VCU_TIPPING_WARNING;
    uint8_t VCU_WARN_REGEN_NOT_ALLOW;
    uint8_t VCU_WARN_REGEN_NOT_EN;
    uint8_t VCU_FSM_INP_BRAKE;
    uint8_t VCU_FSM_INP_PCHG_OK;
    uint8_t VCU_FSM_INP_CRUISE_REQ;
    uint8_t VCU_FSM_INP_REGEN_REQ;
    uint8_t VCU_FSM_INP_REGEN_ENABLE;
    uint8_t VCU_FSM_INP_REGEN_RDY;
    uint8_t VCU_FSM_INP_FORWARD;
    uint8_t VCU_FSM_INP_NEUTRAL;
    uint8_t VCU_FSM_INP_REVERSE;
} vcu_status_t;

typedef struct {
    uint8_t Controls_Leader_Fault;
    uint8_t LightingBoard_Front_Status;
    uint8_t LightingBoard_Left_Status;
    uint8_t LightingBoard_Right_Status;
    uint8_t LightingBoard_Rear_Status;
    uint8_t LightingBoard_Canopy_Status;
} controls_status_t;

typedef struct {
    uint32_t BPS_Precharge_Battery_Voltage;
    uint32_t BPS_Precharge_Array_Voltage;
} bps_precharge_voltages_t;

typedef struct {
    uint32_t VCU_Precharge_Battery_Voltage;
    uint32_t VCU_Precharge_Motor_Voltage;
} vcu_precharge_voltages_t;

typedef struct {
    uint8_t AccelPedal_Main_Pos;
    uint8_t AccelPedal_Redundant_Pos;
    uint8_t BrakePedal_Main_Pos;
    uint8_t BrakePedal_Redundant_Pos;
    uint8_t AccelPedal_Main_Fault;
    uint8_t AccelPedal_Redundant_Fault;
    uint8_t BrakePedal_Main_Fault;
    uint8_t BrakePedal_Redundant_Fault;
    uint8_t Brake_Pressure_1_Fault;
    uint8_t Brake_Pressure_2_Fault;
    uint8_t FrameID_Pedals;
} pedal_status_t;

typedef struct {
    uint8_t Ignition_Array;
    uint8_t Ignition_Motor;
    uint8_t Ignition_Off;
    uint8_t Cruise_Enable;
    uint8_t Cruise_Set;
    uint8_t Gear_Forward;
    uint8_t Gear_Neutral;
    uint8_t Gear_Reverse;
    uint8_t Hazard_Pressed;
    uint8_t Horn_Pressed;
    uint8_t Blinker_Left;
    uint8_t Blinker_Right;
    uint8_t PushToTalk_Pressed;
    uint8_t Regen_Activate;
    uint8_t Regen_Enable;
} driver_input_status_t;

typedef struct {
    int16_t MPPT_Input_Voltage;
    int16_t MPPT_Input_Current;
    int16_t MPPT_Output_Voltage;
    int16_t MPPT_Output_Current;
} mppt_a_powermeasurements_t;

typedef struct {
    uint8_t MPPT_Mode;
    uint8_t MPPT_Fault;
    int8_t MPPT_Enabled;
    int8_t MPPT_AmbientTemperature;
    int8_t MPPT_HeatsinkTemperature;
} mppt_a_status_t;

typedef struct {
    uint8_t MPPT_Sweep_Data_cnt;
    int16_t MPPT_Sweep_Data_Current;
    int16_t MPPT_Sweep_Data_Voltage;
} mppt_a_sweepmeasurements_t;

typedef struct {
    uint8_t MPPT_Set_Enable;
} mppt_a_setmode_t;

typedef struct {
    int16_t MPPT_Set_Sweep_Start;
    int16_t MPPT_Set_Sweep_End;
    uint8_t MPPT_Set_Sweep_Size;
} mppt_a_performsweep_t;

typedef struct {
    int16_t MPPT_SetOutputVoltageLimit;
} mppt_a_setoutputvoltagelimit_t;

typedef struct {
    int16_t MPPT_SetOutputCurrentLimit;
} mppt_a_setoutputcurrentlimit_t;

typedef struct {
    int16_t MPPT_Input_Voltage;
    int16_t MPPT_Input_Current;
    int16_t MPPT_Output_Voltage;
    int16_t MPPT_Output_Current;
} mppt_b_powermeasurements_t;

typedef struct {
    uint8_t MPPT_Mode;
    uint8_t MPPT_Fault;
    int8_t MPPT_Enabled;
    int8_t MPPT_AmbientTemperature;
    int8_t MPPT_HeatsinkTemperature;
} mppt_b_status_t;

typedef struct {
    uint8_t MPPT_Sweep_Data_cnt;
    int16_t MPPT_Sweep_Data_Current;
    int16_t MPPT_Sweep_Data_Voltage;
} mppt_b_sweepmeasurements_t;

typedef struct {
    uint8_t MPPT_Set_Enable;
} mppt_b_setmode_t;

typedef struct {
    int16_t MPPT_Set_Sweep_Start;
    int16_t MPPT_Set_Sweep_End;
    uint8_t MPPT_Set_Sweep_Size;
} mppt_b_performsweep_t;

typedef struct {
    int16_t MPPT_SetOutputVoltageLimit;
} mppt_b_setoutputvoltagelimit_t;

typedef struct {
    int16_t MPPT_SetOutputCurrentLimit;
} mppt_b_setoutputcurrentlimit_t;

typedef struct {
    int16_t MPPT_Input_Voltage;
    int16_t MPPT_Input_Current;
    int16_t MPPT_Output_Voltage;
    int16_t MPPT_Output_Current;
} mppt_c_powermeasurements_t;

typedef struct {
    uint8_t MPPT_Mode;
    uint8_t MPPT_Fault;
    int8_t MPPT_Enabled;
    int8_t MPPT_AmbientTemperature;
    int8_t MPPT_HeatsinkTemperature;
} mppt_c_status_t;

typedef struct {
    uint8_t MPPT_Sweep_Data_cnt;
    int16_t MPPT_Sweep_Data_Current;
    int16_t MPPT_Sweep_Data_Voltage;
} mppt_c_sweepmeasurements_t;

typedef struct {
    uint8_t MPPT_Set_Enable;
} mppt_c_setmode_t;

typedef struct {
    int16_t MPPT_Set_Sweep_Start;
    int16_t MPPT_Set_Sweep_End;
    uint8_t MPPT_Set_Sweep_Size;
} mppt_c_performsweep_t;

typedef struct {
    int16_t MPPT_SetOutputVoltageLimit;
} mppt_c_setoutputvoltagelimit_t;

typedef struct {
    int16_t MPPT_SetOutputCurrentLimit;
} mppt_c_setoutputcurrentlimit_t;

typedef struct {
    int16_t LWS_Angle;
    uint8_t LWS_Speed;
    uint8_t LWS_Fault;
    uint8_t LWS_CalibrationStaus;
    uint8_t LWS_Trimming_Status;
    uint8_t LWS_SF1_5;
    uint8_t LWS_MSG_CNT;
    uint8_t LWS_CHK_SUM;
} lws_standard_t;

typedef struct {
    uint8_t Supplemental_Battery_Fault;
    uint16_t Supplemental_Battery_Voltage;
    int16_t Supplemental_Battery_Current;
    uint8_t FrameID_Supp;
} supp_battery_status_t;

typedef struct {
    uint8_t Supplemental_Charger_Status;
    uint8_t BQ25756E_Error;
    uint8_t BQ25756E_Watchdog;
    int16_t Supplemental_Charge_Current;
    uint16_t Supp_Charge_Current_Limit;
    uint8_t FrameID_Supp_Charger;
} supp_charger_status_t;

typedef struct {
    uint16_t Supplemental_Vicor_Voltage;
    int16_t Supplemental_Vicor_Current;
    uint8_t FrameID_Supp_Charger;
} supp_vicor_stats_t;

typedef struct {
    uint8_t HSS_Channel_idx;
    uint8_t HSS_Fault;
    uint8_t HSS_Enabled;
    uint16_t HSS_Measured_Voltage;
    uint16_t HSS_Measured_Current;
} pdu_status_arr_t;

typedef struct {
    uint8_t HSS_Channel_idx;
    uint8_t HSS_SetSwitch;
} pdu_set_switch_arr_t;

typedef struct {
    uint8_t HSS_Channel_idx;
    uint16_t HSS_Current_Limit;
} pdu_set_current_limit_arr_t;

typedef struct {
    float MC_MotorVelocitySetpoint;
    float MC_MotorCurrentSetpoint;
} mc_drivecommand_t;

typedef struct {
    float MC_MotorPowerSetpoint;
} mc_powercommand_t;

typedef struct {
    uint8_t MC_Reset;
} mc_resetcommand_t;

typedef struct {
    uint32_t MC_TritiumID;
    uint32_t MC_SerialNumber;
} mc_info_t;

typedef struct {
    uint8_t MC_LIMIT_OutputVoltagePWM;
    uint8_t MC_LIMIT_MotorCurrent;
    uint8_t MC_LIMIT_Velocity;
    uint8_t MC_LIMIT_BusCurrent;
    uint8_t MC_LIMIT_BusVoltageUpper;
    uint8_t MC_LIMIT_BusVoltageLower;
    uint8_t MC_LIMIT_MotorTemp;
    uint16_t MC_LIMIT_Reserved;
    uint8_t MC_FAULT_HardwareOverCurrent;
    uint8_t MC_FAULT_SoftwareOverCurrent;
    uint8_t MC_FAULT_DcBusOverVoltage;
    uint8_t MC_FAULT_BadMotorPositionHallSeq;
    uint8_t MC_FAULT_WatchdogCausedLastReset;
    uint8_t MC_FAULT_ConfigRead;
    uint8_t MC_FAULT_15vRailUnderVoltage;
    uint8_t MC_FAULT_DesaturationFault;
    uint8_t MC_FAULT_MotorOverSpeed;
    uint8_t MC_FAULT_Reserved;
    uint16_t MC_ActiveMotor;
    uint8_t MC_TxErrorCount;
    uint8_t MC_RxErrorCount;
} mc_status_t;

typedef struct {
    float MC_BusVoltage;
    float MC_BusCurrent;
} mc_busmeasurement_t;

typedef struct {
    float MC_MotorVelocity;
    float MC_VehicleVelocity;
} mc_velocitymeasurement_t;

typedef struct {
    float MC_PhaseCurrentB;
    float MC_PhaseCurrentC;
} mc_phasecurrentmeasurement_t;

typedef struct {
    float MC_Vq;
    float MC_Vd;
} mc_motorvoltagevectormeasurement_t;

typedef struct {
    float MC_Iq;
    float MC_Id;
} mc_motorcurrentvectormeasurement_t;

typedef struct {
    float MC_BEMFq;
    float MC_BEMFd;
} mc_backemfmeasurementprediction_t;

typedef struct {
    float MC_Supply15V;
} mc_15v_railmeasurement_t;

typedef struct {
    float MC_Supply1V9;
    float MC_Supply3V3;
} mc_3v3_19v_railmeasurement_t;

typedef struct {
    float MC_MotorTemp;
    float MC_HeatsinkTemp;
} mc_motor_tempmeasurement_t;

typedef struct {
    float MC_DspBoardTemp;
} mc_dspboardtempmeasurement_t;

typedef struct {
    float MC_TripOdometer;
    float MC_DCBusAh;
} mc_odometerbusahmeasurement_t;

typedef struct {
    float MC_SlipSpeed;
} mc_slipspeedmeasurement_t;

typedef struct {
    uint8_t Pump_DutyCycle;
    uint8_t Pump_Fault;
    uint16_t FlowRate_1;
    uint16_t FlowRate_2;
} pump_status_t;

typedef struct {
    int16_t Coolant_Temperature_1;
    int16_t Coolant_Temperature_2;
} coolant_temperature_t;

typedef struct {
    uint16_t Radiator_Fan_Speed_Measurement_1;
    uint16_t Radiator_Fan_Speed_Measurement_2;
    uint16_t Radiator_Fan_Speed_Target_1;
    uint16_t Radiator_Fan_Speed_Target_2;
} radiator_fanspeed_t;

typedef struct {
    uint8_t LTC4421_HVDCDC_Selected;
    uint8_t LTC4421_HVDCDC_Fault;
    uint8_t LTC4421_HVDCDC_Valid;
    uint8_t LTC4421_SuppBatt_Selected;
    uint8_t LTC4421_SuppBatt_Fault;
    uint8_t LTC4421_SuppBatt_Valid;
    uint8_t LV_EN_SupplementalBattery;
    uint8_t LV_EN_PowerSupply;
} lv_carrier_status_t;

typedef struct {
    uint16_t Brake_Pressure;
    uint16_t Brake_Pressure_ADC;
    uint8_t FrameID_Pedals;
} brake_pressure_1_t;

typedef struct {
    uint16_t Brake_Pressure;
    uint16_t Brake_Pressure_ADC;
    uint8_t FrameID_Pedals;
} brake_pressure_2_t;

typedef struct {
    uint8_t Lighting_Set_Headlights;
    uint8_t Lighting_Set_Left_Indicator;
    uint8_t Lighting_Set_Right_Indicator;
    uint8_t Lighting_Blink_Sync;
    uint8_t Lighting_Set_Brake;
    uint8_t Lighting_Set_BPS_Strobe;
    uint8_t Lighting_Set_Custom_Mode;
} lighting_command_t;

typedef struct {
    uint8_t Lighting_Board_Fault;
    uint8_t Light_Headlight;
    uint8_t Light_Left_Indicator;
    uint8_t Light_Right_Indicator;
    uint8_t Light_BPS_Strobe;
    uint8_t Light_Brakelight;
    uint8_t Light_CustomMode;
    uint16_t Lighting_Addr_LED_Current;
    uint16_t Lighting_LED0_Current;
    uint16_t Lighting_LED1_Current;
} lighting_front_status_t;

typedef struct {
    uint8_t Lighting_Board_Fault;
    uint8_t Light_Headlight;
    uint8_t Light_Left_Indicator;
    uint8_t Light_Right_Indicator;
    uint8_t Light_BPS_Strobe;
    uint8_t Light_Brakelight;
    uint8_t Light_CustomMode;
    uint16_t Lighting_Addr_LED_Current;
    uint16_t Lighting_LED0_Current;
    uint16_t Lighting_LED1_Current;
} lighting_left_status_t;

typedef struct {
    uint8_t Lighting_Board_Fault;
    uint8_t Light_Headlight;
    uint8_t Light_Left_Indicator;
    uint8_t Light_Right_Indicator;
    uint8_t Light_BPS_Strobe;
    uint8_t Light_Brakelight;
    uint8_t Light_CustomMode;
    uint16_t Lighting_Addr_LED_Current;
    uint16_t Lighting_LED0_Current;
    uint16_t Lighting_LED1_Current;
} lighting_rear_status_t;

typedef struct {
    uint8_t Lighting_Board_Fault;
    uint8_t Light_Headlight;
    uint8_t Light_Left_Indicator;
    uint8_t Light_Right_Indicator;
    uint8_t Light_BPS_Strobe;
    uint8_t Light_Brakelight;
    uint8_t Light_CustomMode;
    uint16_t Lighting_Addr_LED_Current;
    uint16_t Lighting_LED0_Current;
    uint16_t Lighting_LED1_Current;
} lighting_right_status_t;

typedef struct {
    uint8_t Lighting_Board_Fault;
    uint8_t Light_Headlight;
    uint8_t Light_Left_Indicator;
    uint8_t Light_Right_Indicator;
    uint8_t Light_BPS_Strobe;
    uint8_t Light_Brakelight;
    uint8_t Light_CustomMode;
    uint16_t Lighting_Addr_LED_Current;
    uint16_t Lighting_LED0_Current;
    uint16_t Lighting_LED1_Current;
} lighting_canopy_status_t;

typedef struct {
    uint8_t Display_FrameRate;
    uint8_t Camera_Status_Backup;
    uint8_t Camera_Status_Left;
    uint8_t Camera_Status_Right;
} display_status_t;

typedef struct {
} telemetry_status_t;

typedef struct {
    uint8_t BPS_Tap_idx;
    uint16_t BPS_Temperature_Tap_ADC;
    uint8_t FrameID_BPS_Temperature;
} bps_temp_adc_aggregate_arr_t;

typedef struct {
    uint16_t Supp_Battery_Voltage_ADC;
    int16_t Supp_Battery_Current_ADC;
    uint8_t FrameID_Supp;
} supp_measurements_adc_t;

typedef struct {
    uint16_t Supp_Vicor_Voltage_ADC;
    uint16_t Supp_Vicor_Current_ADC;
    uint8_t FrameID_Supp_Charger;
} supp_vicor_measurements_adc_t;

typedef struct {
    uint16_t BrakePedal_Main_ADC;
    uint16_t BrakePedal_Redundant_ADC;
    uint8_t FrameID_Pedals;
} pedal_brake_adc_t;

typedef struct {
    uint16_t AccelPedal_Main_ADC;
    uint16_t AccelPedal_Redundant_ADC;
    uint8_t FrameID_Pedals;
} pedal_accel_adc_t;

typedef struct {
    uint16_t Main_Battery_Current_ADC;
    uint8_t FrameID_Amperes;
} bps_pack_current_adc_t;

typedef struct {
    uint8_t BPS_Segment_idx;
    uint8_t BPS_Tap_idx;
} bps_balance_discharge_t;

typedef struct {
    uint8_t Motor_Command_Source;
} set_motor_cmd_src_t;

typedef struct {
    uint8_t LWS_CCW;
    uint16_t LWS_RES;
} lws_config_t;

typedef struct {
    uint16_t Elcon_VOL_SET;
    uint16_t Elcon_CUR_SET;
    uint8_t Elcon_CONTROL_FLAG;
} elcon_control_t;

typedef struct {
    uint16_t Elcon_AH_NOMINAL;
    uint16_t Elcon_BATTERY_VOL;
    uint16_t Elcon_MAX_CELL_VOL;
    uint8_t Elcon_NUM_CELLS_EXT;
    uint16_t Elcon_VOL_SET;
    uint16_t Elcon_AH_ACTUAL;
    uint16_t Elcon_BATTERY_CHARGE_CUR;
    uint16_t Elcon_CUR_SET;
    uint16_t Elcon_MIN_CELL_VOL;
    uint8_t Elcon_BATTERY_SOC;
    uint16_t Elcon_CELL_OV_THRESH;
    uint16_t Elcon_CELL_UV_THRESH;
    uint8_t Elcon_CONTROL_FLAG;
    uint8_t Elcon_DISCUR_MAX;
    uint8_t Elcon_TEMP_MAX;
    uint8_t Elcon_BATTERY_STATE_OV;
    uint8_t Elcon_BATTERY_STATE_UV;
    uint8_t Elcon_NUM_CELLS;
    uint8_t Elcon_TEMP_MIN;
    uint8_t Elcon_MuxPage;
} elcon_control_mux_t;

typedef struct {
    uint16_t Elcon_VOL_OUT;
    uint16_t Elcon_CUR_OUT;
    uint8_t Elcon_HW_FAULT;
    uint8_t Elcon_OVER_TEMPERATURE;
    uint8_t Elcon_INPUT_VOL_ERROR;
    uint8_t Elcon_START_STATE;
    uint8_t Elcon_CMD_TIMEOUT;
} elcon_ccs_status_t;
