# docker-compose.yml
services:
  dev:
    build:
      platforms:
      - "linux/amd64"
      context: .
      dockerfile: Dockerfile
    container_name: "embedded-sharepoint"
    user: "${HOST_UID}:${HOST_GID}"
    privileged: true

    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - UID=${HOST_UID}
      - GID=${HOST_GID}
    volumes:
      - ${WORKDIR_MOUNT}:/workdir
      - ${SSH_AUTH_SOCK:-/run/host-services/ssh-auth.sock}:/ssh-agent
      - ${HOME}/.ssh:/home/${USER}/.ssh:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      
    working_dir: /workdir

    tty: true
    stdin_open: true
    command: > 
      bash -c 'PS1="\[\e[0;33m\]LHRS@\[\e[1;34m\]Embedded-Sharepoint\[\e[0m\]:\[\e[0;32m\]\w\[\e[0m\]> " exec bash --norc --noprofile -i'
