# docker-compose.yml
services:
  dev:
    build:
      platforms:
      - "linux/amd64"
      context: .
      dockerfile: Dockerfile
    container_name: "embedded-sharepoint"
    privileged: true

    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - ./:/Embedded-Sharepoint
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - ${HOME}/.ssh:/root/.ssh
    working_dir: /Embedded-Sharepoint

    tty: true
    stdin_open: true
    command: ["/bin/bash", "-i"]
