# docker-compose.yml
services:
  dev:
    env_file: .env
    build:
      platforms:
      - "linux/amd64"
      context: .
      dockerfile: Dockerfile
      args:
        REMOTE_USER: ${REMOTE_USER}
        REMOTE_UID: ${REMOTE_UID}
        REMOTE_GID: ${REMOTE_GID}
    container_name: "embedded-sharepoint"
    privileged: true

    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - REMOTE_USER=${REMOTE_USER}
      - REMOTE_UID=${REMOTE_UID}
      - REMOTE_GID=${REMOTE_GID}
      - WORKDIR_MOUNT=${WORKDIR_MOUNT:-$PWD}
    volumes:
      - ${WORKDIR_MOUNT:-$PWD}:/workdir
      - ${SSH_AUTH_SOCK:-/run/host-services/ssh-auth.sock}:/ssh-agent
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      
    working_dir: /workdir

    tty: true
    stdin_open: true
    command: > 
      bash -c 'PS1="\[\e[0;33m\]LHRS@\[\e[1;34m\]Embedded-Sharepoint\[\e[0m\]:\[\e[0;32m\]\w\[\e[0m\]> " exec bash --norc --noprofile -i'
