import os

def define_env(env):
    @env.macro
    def bsp_c_nav():
        """Generate nav entries for all C files generated by MkDoxy."""
        bsp_dir = "BSP"  # folder where MkDoxy generates _8c.md files
        if not os.path.exists(bsp_dir):
            return "  # No files found\n"
        
        md_files = [
            f for f in os.listdir(bsp_dir)
            if f.endswith("_8c.md") and not f.endswith("_source.md")
        ]
        
        nav_lines = ""
        for f in sorted(md_files):
            # Convert _a_d_c_8c.md → ADC.c for display
            name = f.replace("_8c.md", ".c").replace("_", "").upper()
            nav_lines += f"  - {name}: '{bsp_dir}/{f}'\n"
        
        return nav_lines
