#ifndef BOOTLOADER_CONFIG_H_
#define BOOTLOADER_CONFIG_H_

#include "bootloader_hal.h"

#ifndef BOOTLOADER_APP_BASE
#define BOOTLOADER_APP_BASE (0x08010000UL)
#endif

#ifndef BOOTLOADER_APP_MAX_SIZE
#define BOOTLOADER_APP_MAX_SIZE (448UL * 1024UL)
#endif

#ifndef BOOTLOADER_UART_BAUD
#define BOOTLOADER_UART_BAUD (115200U)
#endif

#ifndef BOOTLOADER_UART_INSTANCE
#if defined(USART3)
#define BOOTLOADER_UART_INSTANCE USART3
#elif defined(USART2)
#define BOOTLOADER_UART_INSTANCE USART2
#elif defined(USART1)
#define BOOTLOADER_UART_INSTANCE USART1
#else
#error "No supported UART instance available for bootloader."
#endif
#endif

#ifndef BOOTLOADER_CAN_SYNC_ID
#define BOOTLOADER_CAN_SYNC_ID (0x079U)
#endif

#ifndef BOOTLOADER_CAN_MAX_STD_ID
#define BOOTLOADER_CAN_MAX_STD_ID (0x7FFU)
#endif

#ifndef BOOTLOADER_CAN_ENABLE
#if defined(CAN1)
#define BOOTLOADER_CAN_ENABLE (1U)
#else
#define BOOTLOADER_CAN_ENABLE (0U)
#endif
#endif

#if BOOTLOADER_CAN_ENABLE
#ifndef BOOTLOADER_CAN_INSTANCE
#define BOOTLOADER_CAN_INSTANCE CAN1
#endif

#ifndef BOOTLOADER_CAN_STARTUP_PRESCALER
#define BOOTLOADER_CAN_STARTUP_PRESCALER (40U)
#endif

#ifndef BOOTLOADER_CAN_SJW
#define BOOTLOADER_CAN_SJW CAN_SJW_1TQ
#endif

#ifndef BOOTLOADER_CAN_TIME_SEG1
#define BOOTLOADER_CAN_TIME_SEG1 CAN_BS1_13TQ
#endif

#ifndef BOOTLOADER_CAN_TIME_SEG2
#define BOOTLOADER_CAN_TIME_SEG2 CAN_BS2_2TQ
#endif

#ifndef BOOTLOADER_CAN_GPIO_PORT
#define BOOTLOADER_CAN_GPIO_PORT GPIOB
#endif

#ifndef BOOTLOADER_CAN_RX_PIN
#define BOOTLOADER_CAN_RX_PIN GPIO_PIN_8
#endif

#ifndef BOOTLOADER_CAN_TX_PIN
#define BOOTLOADER_CAN_TX_PIN GPIO_PIN_9
#endif

#ifndef BOOTLOADER_CAN_GPIO_AF
#define BOOTLOADER_CAN_GPIO_AF GPIO_AF9_CAN1
#endif
#endif

#ifndef BOOTLOADER_WRITE_CHUNK_MAX
#define BOOTLOADER_WRITE_CHUNK_MAX (128U)
#endif

#ifndef BOOTLOADER_HANDSHAKE_TIMEOUT_MS
#define BOOTLOADER_HANDSHAKE_TIMEOUT_MS (0U)
#endif

#ifndef BOOTLOADER_APP_STARTUP_WAIT_MS
#define BOOTLOADER_APP_STARTUP_WAIT_MS (3000U)
#endif

#ifndef BOOTLOADER_POST_FLASH_BOOT_DELAY_MS
#define BOOTLOADER_POST_FLASH_BOOT_DELAY_MS (2000U)
#endif

#endif
