name: Test MacOS compilation

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build tests
        run: |
          nix develop --accept-flake-config --command bash -c "
            cd test && make TEST=blinky
          "