name: Test MacOS compilation

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Nix
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/nix
          key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}
          restore-keys: |
            nix-${{ runner.os }}-

      - name: Install Nix
        run: |
          sudo ./nix_install.sh

      - name: Build a test on Mac
        run: |
          . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          sudo nix-env -iA nixpkgs.cacert
          export NIX_SSL_CERT_FILE=/nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt
          nix develop --accept-flake-config --command bash -c "
            cd test && make TEST=blinky
          "
