name: Build Tests

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
       - name: Checkout repository
         uses: actions/checkout@v3

       - name: Install
         run: |
          sudo ./nix_install.sh
          nix develop

       - name: Clean
         run: |
          cd test/
          make clean
          cd ..

       - name: Build tests
         run: |
          cd test/
          bash makeAllTests.sh
          cd ..