name: Build Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Nix
        uses: actions/cache@v3
        with:
          path: |
            /nix/store
            ~/.cache/nix
          key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}
          restore-keys: |
            nix-${{ runner.os }}-

      - name: Install Nix
        run: |
          sudo ./nix_install.sh

      - name: Clean & Build tests
        run: |
          nix develop --accept-flake-config --command bash -c "
            cd test && make clean && bash makeAllTests.sh
          "
