name: Clang Format Check

on:
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format check
        id: clang
        run: |
          # Only check Git-tracked files
          FILES=$(git ls-files '*.c' '*.h')
          echo "Checking files: $FILES"

          # Run clang-format and capture diff
          FAIL=0
          OUTPUT=""
          for f in $FILES; do
            DIFF=$(clang-format -style=file "$f" | diff -u "$f" - || true)
            if [ -n "$DIFF" ]; then
              FAIL=1
              OUTPUT="$OUTPUT\n\n\`\`\`diff\n$DIFF\n\`\`\`"
            fi
          done

          if [ $FAIL -ne 0 ]; then
            echo "clang-format found issues"
            echo "status=fail" >> $GITHUB_OUTPUT
            # Store diff in output for PR comment
            echo "diff<<EOF" >> $GITHUB_OUTPUT
            echo -e "$OUTPUT" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "status=ok" >> $GITHUB_OUTPUT
          fi

      - name: Comment PR with clang-format diff
        if: failure() && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: clang-format
          message: |
            ⚠️ **clang-format check failed**  
            Please run `clang-format` locally and commit the changes.

            The following diffs show what needs fixing:

            ${{ steps.clang.outputs.diff }}
